### ISSUE TITLE
When following the example to import local modules the error "ModuleNotFoundError: No module named 'data'" happens

### ISSUE THREAD

**Issue by douglasdcm** [pyscript/pyscript#1001]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

Hi, I'm new on PyScript, so I was following the tutorial to [declare local modules](https://docs.pyscript.net/latest/tutorials/getting-started.html#local-modules) to train it. I put the html and data.py files in the same folder and opened the html file in a browser, but data module wasn't found. I tried to change the "script defer src=" to all available tags, but the error persisted.

### What browsers are you seeing the problem on? (if applicable)

Chrome, Other

### Console info

```shell
# Here are the complete log from browser console

logger.ts:39 [py-config] config set from inline
logger.ts:39 [py-config] config set: {name: undefined, description: undefined, version: undefined, type: 'app', author_name: undefined, …}
logger.ts:39 [py-config] Initializing runtimes
logger.ts:39 [pyscript/pyodide] Runtime config: {name: 'pyodide-0.21.2', lang: 'python', src: 'https://cdn.jsdelivr.net/pyodide/v0.21.2/full/pyodide.js'}
logger.ts:39 [pyscript/main] checking for py-config
logger.ts:39 [pyscript/main] add py-loader
logger.ts:39 [py-loader] Loading runtime...
logger.ts:39 [pyscript/pyodide] Loading pyodide
DevTools failed to load source map: Could not load content for https://cdn.jsdelivr.net/pyodide/v0.21.2/full/pyodide.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
pyodide.asm.js:10 Python initialization complete
logger.ts:39 [pyscript/pyodide] pyodide.loadPackage: micropip
logger.ts:39 [pyscript/pyodide] Loading micropip, pyparsing, packaging, distutils
logger.ts:39 [pyscript/pyodide] Loaded micropip, packaging, pyparsing, distutils
logger.ts:39 [pyscript/pyodide] importing pyscript.py
pyodide.asm.js:10 [Violation] 'setTimeout' handler took 848ms
logger.ts:39 [pyscript/pyodide] pyodide loaded and initialized
logger.ts:39 [py-loader] Runtime created...
logger.ts:39 [py-loader] Initializing components...
logger.ts:39 [py-script] py-mount: found 0 elements
logger.ts:39 [py-config] Loading env:  (2) ['numpy', 'matplotlib']
logger.ts:39 [pyscript/pyodide] micropip install numpy,matplotlib
pyodide.asm.js:10 distutils already loaded from default channel
pyodide.asm.js:10 packaging already loaded from default channel
pyodide.asm.js:10 pyparsing already loaded from default channel
pyodide.asm.js:10 Loading numpy, matplotlib, cycler, six, fonttools, kiwisolver, pillow, python-dateutil, pytz
pyodide.asm.js:10 Loaded cycler, six, fonttools, python-dateutil, pytz, kiwisolver, pillow, matplotlib, numpy
logger.ts:39 [py-config] Paths to load:  []
logger.ts:39 [py-config] All paths loaded
logger.ts:39 [py-loader] Initializing scripts...
logger.ts:39 [py-loader] Running post initializers...
logger.ts:39 [py-loader] Closing
logger.ts:39 [py-script] Initializing py-* event handlers...
logger.ts:39 [pyscript/runtime] PyScript page fully initialized
pyodide.asm.js:10 [Violation] 'setTimeout' handler took 4105ms
logger.ts:39 [pyscript/base] PythonError: Traceback (most recent call last):
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 232, in __step
    result = coro.send(None)
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 506, in eval_code_async
    await CodeRunner(
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 357, in run_async
    coroutine = eval(self.code, globals, locals)
  File "<exec>", line 2, in <module>
ModuleNotFoundError: No module named 'data'

fn @ logger.ts:39
evaluate @ base.ts:136
await in evaluate (async)
initialize @ runtime.ts:77
await in initialize (async)
(anonymous) @ pyconfig.ts:107
load (async)
loadRuntimes @ pyconfig.ts:106
connectedCallback @ pyconfig.ts:70
(anonymous) @ main.ts:12
(anonymous) @ main.ts:26
```

### Additional Context

I did the same test using the [Liver Server](https://github.com/ritwickdey/vscode-live-server-plus-plus) in VSCode, but the error were the same.

**Comment by madhur-tandon** [comment]
`Paths to load:  []` is empty as seen here, did you declare the `py-config` as described in the tutorial?
Especially the section about:
```
[[fetch]]
        files = ["./data.py"]
```

**Comment by douglasdcm** [comment]
Hi, @madhur-tandon thank you for the quick reply. I'll past here the html and data content

my.html
```
<html>
    <head>
      <link rel="stylesheet" href="https://pyscript.net/latest/pyscript.css" />
      <script defer src="https://pyscript.net/latest/pyscript.js"></script>
    </head>

  <body>
    <h1>Let's plot random numbers</h1>
    <div id="plot"></div>
    <py-config type="toml">
        packages = ["numpy", "matplotlib"]

        [[fetch]]
        files = ["./data.py"]
    </py-config>
    <py-script output="plot">
      import matplotlib.pyplot as plt
      from data import make_x_and_y
      x, y = make_x_and_y(n=1000)
      fig, ax = plt.subplots()
      ax.scatter(x, y)
      fig
    </py-script>
  </body>
</html>
```

data.py
```
# data.py
import numpy as np


def make_x_and_y(n):
    x = np.random.randn(n)
    y = np.random.randn(n)
    return x, y

```

**Comment by madhur-tandon** [comment]
Aah, the `script` is `https://pyscript.net/latest/pyscript.js` while the `[[fetch]]` tag should be available in the next release. You can perhaps use the `unstable` URL i.e. `https://pyscript.net/unstable/pyscript.js`

**Comment by douglasdcm** [comment]
I changed the latest to unstable and the message bellow appered
```
The 'output' attribute is deprecated and ignored. You should use 'display()' to output the content to a specific element. For example display(myElement, target="divID").
```

I changed the <py-script **output**="plot"> to <py-script **display**="plot"> in html file and at least the error is not happening, but the figure is not shown. Here is the new html file

```
<html>
    <head>
      <link rel="stylesheet" href="https://pyscript.net/latest/pyscript.css" />
      <script defer src="https://pyscript.net/unstable/pyscript.js"></script>
    </head>

  <body>
    <h1>Let's plot random numbers</h1>
    <div id="plot"></div>
    <py-config type="toml">
        packages = ["numpy", "matplotlib"]

        [[fetch]]
        files = ["./data.py"]
    </py-config>
    <py-script display="plot">
      import matplotlib.pyplot as plt
      from data import make_x_and_y
      x, y = make_x_and_y(n=1000)
      fig, ax = plt.subplots()
      ax.scatter(x, y)
      fig
    </py-script>
  </body>
</html>
```

**Comment by douglasdcm** [comment]
I'll do this suggested change display(myElement, target="divID") and try again

**Comment by madhur-tandon** [comment]
Tagging @marimeireles and @FabioRosado here for help with `display` / `output` stuff.

**Comment by FabioRosado** [comment]
Hi @douglasdcm 👋

It seems we may need to improve the message in the banner 😄

You should be able to display your plot using `display(plot, target="plot"`)

Can you give that a try and let us know if you encounter any issues?

**Comment by douglasdcm** [comment]
Hi, @FabioRosado thank you!

I may doing something wrong. I added the display at the end of the "py-script" block, but a new error happens. I noticed there is a div with an id="plot", but I don't know what is missing.
Here is the error
```
Traceback (most recent call last):
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 435, in eval_code
    .run(globals, locals)
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 304, in run
    coroutine = eval(self.code, globals, locals)
  File "<exec>", line 7, in <module>
NameError: name 'plot' is not defined
```

html
```
<html>
    <head>
      <link rel="stylesheet" href="https://pyscript.net/latest/pyscript.css" />
      <script defer src="https://pyscript.net/unstable/pyscript.js"></script>
    </head>

  <body>
    <h1>Let's plot random numbers</h1>
    <div id="plot"></div>
    <py-config type="toml">
        packages = ["numpy", "matplotlib"]

        [[fetch]]
        files = ["./data.py"]
    </py-config>
    <py-script display="plot">
      import matplotlib.pyplot as plt
      from data import make_x_and_y
      x, y = make_x_and_y(n=1000)
      fig, ax = plt.subplots()
      ax.scatter(x, y)
      fig
      display(plot, target="plot")
    </py-script>
  </body>
</html>
```

Log trace
```
pyscript.js:1826 [pyscript/main] searching for <py-config>
pyscript.js:1826 [py-config] loading <py-config> content
pyscript.js:1826 [pyscript/main] config loaded:
{
  "type": "app",
  "schema_version": 1,
  "runtimes": [
    {
      "src": "https://cdn.jsdelivr.net/pyodide/v0.21.3/full/pyodide.js",
      "name": "pyodide-0.21.3",
      "lang": "python"
    }
  ],
  "packages": [
    "numpy",
    "matplotlib"
  ],
  "fetch": [
    {
      "files": [
        "./data.py"
      ]
    }
  ],
  "plugins": [],
  "pyscript": {
    "version": "2022.11.1.dev",
    "time": "2022-12-01T15:58:53.489Z"
  }
}
pyscript.js:1826 [py-splashscreen] add py-splashscreen
pyscript.js:1826 [py-terminal] No <py-terminal> found, adding one
pyscript.js:1826 [pyscript/main] Initializing runtime
pyscript.js:1826 [pyscript/pyodide] Runtime config: {name: 'pyodide-0.21.3', lang: 'python', src: 'https://cdn.jsdelivr.net/pyodide/v0.21.3/full/pyodide.js'}
pyscript.js:1826 [pyscript/main] Downloading pyodide-0.21.3...
pyscript.js:1826 [pyscript/main] Python startup...
pyscript.js:1826 [pyscript/pyodide] Loading pyodide
DevTools failed to load source map: Could not load content for chrome-extension://mooikfkahbdckldjjndioackbalphokd/assets/atoms.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for chrome-extension://mooikfkahbdckldjjndioackbalphokd/assets/polyfills.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for chrome-extension://mooikfkahbdckldjjndioackbalphokd/assets/escape.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for chrome-extension://mooikfkahbdckldjjndioackbalphokd/assets/playback.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for chrome-extension://mooikfkahbdckldjjndioackbalphokd/assets/record.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
pyscript.js:26710 Python initialization complete
pyscript.js:1826 [pyscript/pyodide] pyodide.loadPackage: micropip
pyscript.js:1826 [pyscript/pyodide] Loading micropip, pyparsing, packaging, distutils
pyscript.js:1826 [pyscript/pyodide] Loaded pyparsing, packaging, distutils, micropip
pyscript.js:1826 [pyscript/pyodide] pyodide loaded and initialized
pyscript.js:1826 [pyscript/main] Python ready!
pyscript.js:1826 [pyscript/main] Setting up virtual environment...
pyscript.js:1826 [pyscript/main] importing pyscript
pyscript.js:26714 /lib/python3.10/site-packages/pyodide/__init__.py:74: FutureWarning: pyodide.create_proxy has been moved to pyodide.ffi.create_proxy Accessing it through the pyodide module is deprecated.
pyscript.js:26714   warn(
pyscript.js:1826 [pyscript/main] DEPRECATION WARNING: 'micropip', 'Element', 'console', 'document' and several other objects form the pyscript module (with the exception of 'display') will be be removed from the Python global namespace in the following release. To avoid errors in future releases use import from pyscript instead. For instance: from pyscript import micropip, Element, console, document
fn @ pyscript.js:1826
setupVirtualEnv @ pyscript.js:27101
await in setupVirtualEnv (async)
afterRuntimeLoad @ pyscript.js:27062
await in afterRuntimeLoad (async)
(anonymous) @ pyscript.js:27045
load (async)
loadRuntime @ pyscript.js:27044
_realMain @ pyscript.js:27004
main @ pyscript.js:26983
(anonymous) @ pyscript.js:27203
(anonymous) @ pyscript.js:27214
pyscript.js:1826 [pyscript/main] Packages to install:  (2) ['numpy', 'matplotlib']
pyscript.js:1826 [pyscript/pyodide] micropip install numpy,matplotlib
pyodide.asm.js:10 distutils already loaded from default channel
pyodide.asm.js:10 packaging already loaded from default channel
pyodide.asm.js:10 pyparsing already loaded from default channel
pyodide.asm.js:10 Loading numpy, matplotlib, cycler, six, fonttools, kiwisolver, pillow, python-dateutil, pytz
pyodide.asm.js:10 Loaded six, cycler, kiwisolver, python-dateutil, fonttools, pytz, pillow, numpy, matplotlib
pyscript.js:1826 [pyscript/main] Paths to fetch:  ['./data.py']
pyscript.js:1826 [pyscript/main]   fetching path: ./data.py
pyscript.js:1826 [pyscript/main] All paths fetched
pyscript.js:1826 [pyscript/main] Python plugins to fetch:  []
pyscript.js:1826 [pyscript/main] All plugins fetched
pyscript.js:1826 [py-script] py-mount: found 0 elements
pyscript.js:1826 [py-terminal] Registering stdio listener
pyscript.js:1826 [pyscript/main] Executing <py-script> tags...
pyscript.js:1826 [pyscript/main] Initializing web components...
pyscript.js:1826 [py-script] Initializing py-* event handlers...
pyscript.js:1826 [pyscript/main] Startup complete
pyscript.js:1826 [py-splashscreen] Closing
pyscript.js:1826 [pyscript/main] PyScript page fully initialized
pyscript.js:1826 [pyexec] Python exception:
Traceback (most recent call last):
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 435, in eval_code
    .run(globals, locals)
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 304, in run
    coroutine = eval(self.code, globals, locals)
  File "<exec>", line 7, in <module>
NameError: name 'plot' is not defined

fn @ pyscript.js:1826
displayPyException @ pyscript.js:2393
pyExec @ pyscript.js:2364
connectedCallback @ pyscript.js:2446
await in connectedCallback (async)
executeScripts @ pyscript.js:27185
afterRuntimeLoad @ pyscript.js:27069
await in afterRuntimeLoad (async)
(anonymous) @ pyscript.js:27045
load (async)
loadRuntime @ pyscript.js:27044
_realMain @ pyscript.js:27004
main @ pyscript.js:26983
(anonymous) @ pyscript.js:27203
(anonymous) @ pyscript.js:27214
pyodide.asm.js:10 [Violation] 'setTimeout' handler took 108ms
DevTools failed to load source map: Could not load content for https://pyscript.net/unstable/pyscript.js.map: Load canceled due to load timeout
```

**Comment by FabioRosado** [comment]
Apologies I was on my phone and didn't see the code properly.

Your graph variable is called `fig` not `plot`, you will need to change the name to:

`display(fig, target="plot")`

**Comment by douglasdcm** [comment]
Thank you @FabioRosado ! Now it is working fine. The Scatter plot has been shown correctly :)
Can I close this issue?

**Comment by madhur-tandon** [comment]
Yes, we can close this. Thanks @douglasdcm.
The issues that you face are basically because the documentation represents the current state of the repository while those `newer` features / paradigms aren't available in the last release that is present at the `/latest` URL.
