### ISSUE TITLE
Error While importing Pytube and Os Library

### ISSUE THREAD

**Issue by Python-Automation-Man** [pyscript/pyscript#1061]
`(PY1001): Unable to install package(s) 'from pytube import Youtube'. Reason: Traceback (most recent call last): File "/lib/python3.10/site-packages/packaging/requirements.py", line 102, in __init__ req = REQUIREMENT.parseString(requirement_string) File "/lib/python3.10/site-packages/pyparsing/core.py", line 1141, in parse_string raise exc.with_traceback(None) pyparsing.exceptions.ParseException: Expected string_end, found 'pytube' (at char 5), (line:1, col:6) During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/lib/python3.10/asyncio/futures.py", line 201, in result raise self._exception File "/lib/python3.10/asyncio/tasks.py", line 234, in __step result = coro.throw(exc) File "/lib/python3.10/site-packages/micropip/_micropip.py", line 548, in install await transaction.gather_requirements(requirements) File "/lib/python3.10/site-packages/micropip/_micropip.py", line 305, in gather_requirements await gather(*requirement_promises) File "/lib/python3.10/asyncio/futures.py", line 284, in __await__ yield self # This tells Task to wait for completion. File "/lib/python3.10/asyncio/tasks.py", line 304, in __wakeup future.result() File "/lib/python3.10/asyncio/futures.py", line 201, in result raise self._exception File "/lib/python3.10/asyncio/tasks.py", line 232, in __step result = coro.send(None) File "/lib/python3.10/site-packages/micropip/_micropip.py", line 312, in add_requirement return await self.add_requirement_inner(Requirement(req)) File "/lib/python3.10/site-packages/packaging/requirements.py", line 104, in __init__ raise InvalidRequirement( packaging.requirements.InvalidRequirement: Parse error at "'pytube i'": Expected string_end . Please open an issue at https://github.com/pyscript/pyscript/issues/new if you require help or you think it's a bug.`

  <head>
    <title>Ice Cream Picker</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://pyscript.net/latest/pyscript.css" />
    <script defer src="https://pyscript.net/latest/pyscript.js"></script>
  </head>
  <body>
  <py-config>
      packages = ["from pytube import Youtube"]
  </py-config>
    <pyscript>
        import os
        from pytube import YouTube
            def youtubedownloader():
                youtube = YouTube('https://www.youtube.com/watch?v=5m8BAffnuA8&list=PLTgRMOcmRb3PQEztkPnMvAeehReJPoSNP')
                my_video = youtube.streams.first()
                username = os.getlogin()
                my_video.download(f'C:/Users/{username}/downloads')

    </pyscript>

**Comment by Python-Automation-Man** [comment]
`<html>
  <head>
    <title>Ice Cream Picker</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://pyscript.net/latest/pyscript.css" />
    <script defer src="https://pyscript.net/latest/pyscript.js"></script>
  </head>
  <body>
  <py-config>
      packages = ["from pytube import Youtube"]
  </py-config>
    <pyscript>
        import os
        from pytube import YouTube
            def youtubedownloader():
                youtube = YouTube('https://www.youtube.com/watch?v=5m8BAffnuA8&list=PLTgRMOcmRb3PQEztkPnMvAeehReJPoSNP')
                my_video = youtube.streams.first()
                username = os.getlogin()
                my_video.download(f'C:/Users/{username}/downloads')


            youtubedownloader()
    </pyscript>

  </body>
</html>`
