### ISSUE TITLE
Example test - panel stream fails (Tabulator not defined)

### ISSUE THREAD

**Issue by FabioRosado** [pyscript/pyscript#1109]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a duplication
- [X] I already searched in Google and didn't find any good information or help

### What is the issue/comment/problem?

Just had a failure on #1082, looking at the failure it doesn't seem originated by any changes to the runtimes renaming.

```python
==================================== ERRORS ====================================
________ ERROR at teardown of TestExamples.test_panel_stream[chromium] _________
[gw1] linux -- Python 3.9.15 /home/runner/work/pyscript/pyscript/pyscriptjs/env/bin/python

self = <integration.test_zz_examples.TestExamples object at 0x7f8860fb1eb0>

    def teardown_method(self):
        # we call check_js_errors on teardown: this means that if there are still
        # non-cleared errors, the test will fail. If you expect errors in your
        # page and they should not cause the test to fail, you should call
        # self.check_js_errors() in the test itself.
>       self.check_js_errors()

tests/integration/support.py:134: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <integration.test_zz_examples.TestExamples object at 0x7f8860fb1eb0>
expected_messages = [], js_errors = [Error('Tabulator is not defined')]

    def check_js_errors(self, *expected_messages):
        """
        Check whether JS errors were reported.
    
        expected_messages is a list of strings of errors that you expect they
        were raised in the page.  They are checked using a simple 'in' check,
        equivalent to this:
            if expected_message in actual_error_message:
                ...
    
        If an error was expected but not found, it raises
        DidNotRaiseJsError().
    
        If there are MORE errors other than the expected ones, it raises JsErrors.
    
        Upon return, all the errors are cleared, so a subsequent call to
        check_js_errors will not raise, unless NEW JS errors have been reported
        in the meantime.
        """
        expected_messages = list(expected_messages)
        js_errors = self._js_errors[:]
    
        for i, msg in enumerate(expected_messages):
            for j, error in enumerate(js_errors):
                if msg is not None and error is not None and msg in error.message:
                    # we matched one expected message with an error, remove both
                    expected_messages[i] = None
                    js_errors[j] = None
    
        # if everything is find, now expected_messages and js_errors contains
        # only Nones. If they contain non-None elements, it means that we
        # either have messages which are expected-but-not-found or errors
        # which are found-but-not-expected.
        expected_messages = [msg for msg in expected_messages if msg is not None]
        js_errors = [err for err in js_errors if err is not None]
        self.clear_js_errors()
    
        if expected_messages:
            # expected-but-not-found
            raise JsErrorsDidNotRaise(expected_messages, js_errors)
    
        if js_errors:
            # found-but-not-expected
>           raise JsErrors(js_errors)
E           integration.support.JsErrors: JS errors found: 1
E           ReferenceError: Tabulator is not defined
E               at C.render (https://unpkg.com/@holoviz/panel@0.13.1/dist/panel.min.js:52:6005)
E               at a.onload (https://unpkg.com/@holoviz/panel@0.13.1/dist/panel.min.js:52:15216)

tests/integration/support.py:186: JsErrors
---------------------------- Captured stdout setup -----------------------------

----------------------------- Captured stdout call -----------------------------
[  0.00 page.goto       ] examples/panel_stream.html
[  0.01 request         ] 200 - fake_server - http://fake_server/examples/panel_stream.html
[  0.02 request         ] 200 - CACHED - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css
[  0.03 request         ] 200 - CACHED - https://unpkg.com/@holoviz/panel@0.13.1/dist/css/widgets.css
[  0.03 request         ] 200 - CACHED - https://unpkg.com/@holoviz/panel@0.13.1/dist/css/markdown.css
[  0.04 request         ] 200 - CACHED - https://cdn.bokeh.org/bokeh/release/bokeh-2.4.2.js
[  0.06 request         ] 200 - CACHED - https://cdn.bokeh.org/bokeh/release/bokeh-widgets-2.4.2.min.js
[  0.06 request         ] 200 - CACHED - https://cdn.bokeh.org/bokeh/release/bokeh-tables-2.4.2.min.js
[  0.06 request         ] 200 - CACHED - https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css
[  0.07 request         ] 200 - CACHED - https://unpkg.com/@holoviz/panel@0.13.1/dist/bundled/bootstraptemplate/bootstrap.css
[  0.07 request         ] 200 - CACHED - https://unpkg.com/@holoviz/panel@0.13.1/dist/bundled/defaulttheme/default.css
[  0.07 request         ] 200 - CACHED - https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js
[  0.07 request         ] 200 - CACHED - https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js
[  0.07 request         ] 200 - fake_server - http://fake_server/build/pyscript.css
[  0.07 request         ] 200 - fake_server - http://fake_server/examples/assets/css/examples.css
[ 31.20 request         ] 200 - NETWORK - https://unpkg.com/@holoviz/panel@0.13.1/dist/panel.min.js
[ 31.22 request         ] 200 - fake_server - http://fake_server/build/pyscript.js
[ 31.31 request         ] 200 - fake_server - http://fake_server/examples/logo.png
***** Error inside Fake_Server.router *****
Traceback (most recent call last):
  File "/home/runner/work/pyscript/pyscript/pyscriptjs/tests/integration/support.py", line 761, in fetch_from_network
    api_response = self.page.request.fetch(request)
  File "/home/runner/work/pyscript/pyscript/pyscriptjs/env/lib/python3.9/site-packages/playwright/sync_api/_generated.py", line 17752, in fetch
    self._sync(
  File "/home/runner/work/pyscript/pyscript/pyscriptjs/env/lib/python3.9/site-packages/playwright/_impl/_sync_base.py", line 104, in _sync
    return task.result()
  File "/home/runner/work/pyscript/pyscript/pyscriptjs/env/lib/python3.9/site-packages/playwright/_impl/_fetch.py", line 285, in fetch
    return await self._inner_fetch(
  File "/home/runner/work/pyscript/pyscript/pyscriptjs/env/lib/python3.9/site-packages/playwright/_impl/_fetch.py", line 372, in _inner_fetch
    response = await self._channel.send(
  File "/home/runner/work/pyscript/pyscript/pyscriptjs/env/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 44, in send
    return await self._connection.wrap_api_call(
  File "/home/runner/work/pyscript/pyscript/pyscriptjs/env/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 419, in wrap_api_call
    return await cb()
  File "/home/runner/work/pyscript/pyscript/pyscriptjs/env/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 79, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Request timed out after 30000ms
=========================== logs ===========================
→ GET https://unpkg.com/tabulator-tables@4.9.3/dist/js/tabulator.js
  user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/109.0.5414.46 Safari/537.36
  accept: */*
  accept-encoding: gzip,deflate,br
  referer: http://fake_server/
  sec-ch-ua: 
  sec-ch-ua-mobile: ?0
  sec-ch-ua-platform: 
============================================================

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/pyscript/pyscript/pyscriptjs/tests/integration/support.py", line 692, in router
    return self._router(route)
  File "/home/runner/work/pyscript/pyscript/pyscriptjs/tests/integration/support.py", line 729, in _router
    resp = self.fetch_from_network(route.request)
  File "/home/runner/work/pyscript/pyscript/pyscriptjs/tests/integration/support.py", line 765, in fetch_from_network
    api_response = self.page.request.fetch(request)
  File "/home/runner/work/pyscript/pyscript/pyscriptjs/env/lib/python3.9/site-packages/playwright/sync_api/_generated.py", line 17752, in fetch
    self._sync(
  File "/home/runner/work/pyscript/pyscript/pyscriptjs/env/lib/python3.9/site-packages/playwright/_impl/_sync_base.py", line 104, in _sync
    return task.result()
  File "/home/runner/work/pyscript/pyscript/pyscriptjs/env/lib/python3.9/site-packages/playwright/_impl/_fetch.py", line 285, in fetch
    return await self._inner_fetch(
  File "/home/runner/work/pyscript/pyscript/pyscriptjs/env/lib/python3.9/site-packages/playwright/_impl/_fetch.py", line 372, in _inner_fetch
    response = await self._channel.send(
  File "/home/runner/work/pyscript/pyscript/pyscriptjs/env/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 44, in send
    return await self._connection.wrap_api_call(
  File "/home/runner/work/pyscript/pyscript/pyscriptjs/env/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 419, in wrap_api_call
    return await cb()
  File "/home/runner/work/pyscript/pyscript/pyscriptjs/env/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 79, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Request timed out after 30000ms
=========================== logs ===========================
→ GET https://unpkg.com/tabulator-tables@4.9.3/dist/js/tabulator.js
  user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/109.0.5414.46 Safari/537.36
  accept: */*
  accept-encoding: gzip,deflate,br
  referer: http://fake_server/
  sec-ch-ua: 
  sec-ch-ua-mobile: ?0
  sec-ch-ua-platform: 
============================================================

[ 60.63 console.error   ] Failed to load resource: net::ERR_FAILED
[ 60.81 console.log     ] [bokeh] setting log level to: 'info'
[ 60.92 console.info    ] [pyscript/main] searching for <py-config>
[ 60.92 console.info    ] [py-config] loading <py-config> content
[ 60.92 console.info    ] [pyscript/main] config loaded:
{
  "type": "app",
  "schema_version": 1,
  "runtimes": [],
  "interpreters": [
    {
      "src": "https://cdn.jsdelivr.net/pyodide/v0.21.3/full/pyodide.js",
      "name": "pyodide-0.21.3",
      "lang": "python"
    }
  ],
  "packages": [
    "bokeh",
    "numpy",
    "pandas",
    "panel==0.13.1"
  ],
  "fetch": [],
  "plugins": [
    "../build/plugins/python/py_tutor.py"
  ],
  "pyscript": {
    "version": "2022.12.1.dev",
    "time": "2023-01-16T14:28:48.442Z"
  }
}
[ 60.93 console.info    ] [py-splashscreen] add py-splashscreen
[ 60.93 console.info    ] [py-terminal] No <py-terminal> found, adding one
[ 60.93 console.info    ] [pyscript/main] Initializing interpreter
[ 60.93 console.info    ] [pyscript/pyodide] Interpreter config: {name: pyodide-0.21.3, lang: python, src: https://cdn.jsdelivr.net/pyodide/v0.21.3/full/pyodide.js}
[ 60.93 console.info    ] [pyscript/main] Downloading pyodide-0.21.3...
[ 60.93 request         ] 200 - CACHED - https://cdn.jsdelivr.net/pyodide/v0.21.3/full/pyodide.js
[ 60.95 console.info    ] [pyscript/main] Python startup...
[ 60.95 console.info    ] [pyscript/pyodide] Loading pyodide
[ 60.95 request         ] 200 - CACHED - https://cdn.jsdelivr.net/pyodide/v0.21.3/full/pyodide_py.tar
[ 60.97 request         ] 200 - CACHED - https://cdn.jsdelivr.net/pyodide/v0.21.3/full/pyodide.asm.js
[ 61.24 request         ] 200 - CACHED - https://cdn.jsdelivr.net/pyodide/v0.21.3/full/pyodide.asm.data
[ 61.27 request         ] 200 - CACHED - https://cdn.jsdelivr.net/pyodide/v0.21.3/full/repodata.json
[ 61.39 request         ] 200 - CACHED - https://cdn.jsdelivr.net/pyodide/v0.21.3/full/pyodide.asm.wasm
[ 63.98 console.log     ] Python initialization complete
[ 63.98 console.info    ] [pyscript/pyodide] Found packages in configuration to install. Loading micropip...
[ 63.98 console.info    ] [pyscript/pyodide] pyodide.loadPackage: micropip
[ 63.98 console.info    ] [pyscript/pyodide] Loading micropip, pyparsing, packaging, distutils
[ 63.99 request         ] 200 - CACHED - https://cdn.jsdelivr.net/pyodide/v0.21.3/full/micropip-0.1-py3-none-any.whl
[ 64.00 request         ] 200 - CACHED - https://cdn.jsdelivr.net/pyodide/v0.21.3/full/pyparsing-3.0.9-py3-none-any.whl
[ 64.00 request         ] 200 - CACHED - https://cdn.jsdelivr.net/pyodide/v0.21.3/full/packaging-21.3-py3-none-any.whl
[ 64.01 request         ] 200 - CACHED - https://cdn.jsdelivr.net/pyodide/v0.21.3/full/distutils.tar
[ 64.25 console.info    ] [pyscript/pyodide] Loaded pyparsing, packaging, distutils, micropip
[ 64.25 console.info    ] [pyscript/pyodide] pyodide loaded and initialized
[ 64.25 console.info    ] [pyscript/main] Python ready!
[ 64.25 console.info    ] [pyscript/main] Setting up virtual environment...
[ 64.25 console.info    ] [pyscript/main] importing pyscript
[ 64.30 console.log     ] /lib/python3.10/site-packages/pyodide/__init__.py:74: FutureWarning: pyodide.create_proxy has been moved to pyodide.ffi.create_proxy Accessing it through the pyodide module is deprecated.
[ 64.30 console.log     ]   warn(
[ 64.97 console.info    ] [pyscript/main] Packages to install:  [bokeh,numpy,pandas,panel==0.13.1]
[ 64.97 console.info    ] [pyscript/pyodide] micropip install bokeh,numpy,pandas,panel==0.13.1
[ 65.01 request         ] 200 - CACHED - https://pypi.org/pypi/panel/json
[ 65.61 request         ] 200 - CACHED - https://files.pythonhosted.org/packages/12/90/9bde3e224f5f5a616036401b3f70b54f59a775cc7d630f040d7ce8363560/panel-0.13.1-py2.py3-none-any.whl
[ 68.63 request         ] 200 - CACHED - https://pypi.org/pypi/param/json
[ 68.66 request         ] 200 - CACHED - https://pypi.org/pypi/pyviz-comms/json
[ 68.67 request         ] 200 - CACHED - https://pypi.org/pypi/markdown/json
[ 68.70 request         ] 200 - CACHED - https://pypi.org/pypi/requests/json
[ 68.72 request         ] 200 - CACHED - https://pypi.org/pypi/pyct/json
[ 68.76 request         ] 200 - CACHED - https://files.pythonhosted.org/packages/5a/81/87a391d444c39b08ac564667a77cef8abdcdd4105cd5509d83711fe2544c/param-1.12.3-py2.py3-none-any.whl
[ 68.82 request         ] 200 - CACHED - https://files.pythonhosted.org/packages/2f/78/72bec6805be44a11dc80e949752fcaacc21661c3423e26623263d19a73d1/pyviz_comms-2.2.1-py2.py3-none-any.whl
[ 68.87 request         ] 200 - CACHED - https://files.pythonhosted.org/packages/86/be/ad281f7a3686b38dd8a307fa33210cdf2130404dfef668a37a4166d737ca/Markdown-3.4.1-py3-none-any.whl
[ 68.91 request         ] 200 - CACHED - https://files.pythonhosted.org/packages/d2/f4/274d1dbe96b41cf4e0efb70cbced278ffd61b5c7bb70338b62af94ccb25b/requests-2.28.2-py3-none-any.whl
[ 68.96 request         ] 200 - CACHED - https://files.pythonhosted.org/packages/71/76/52ce7aec26b0171939d3b[384](https://github.com/pyscript/pyscript/actions/runs/3931249013/jobs/6722258055#step:10:385)3acd011f8eb297b2a569e992691bb296[418](https://github.com/pyscript/pyscript/actions/runs/3931249013/jobs/6722258055#step:10:419)5/pyct-0.4.8-py2.py3-none-any.whl
[ 69.19 request         ] 200 - CACHED - https://pypi.org/pypi/charset-normalizer/json
[ 69.23 request         ] 200 - CACHED - https://pypi.org/pypi/urllib3/json
[ 69.25 request         ] 200 - CACHED - https://pypi.org/pypi/idna/json
[ 69.38 request         ] 200 - CACHED - https://files.pythonhosted.org/packages/68/2b/02e9d6a98ddb73fa238d559a9edcc30b247b8dc4ee848b6184c936e99dc0/charset_normalizer-3.0.1-py3-none-any.whl
[ 69.45 request         ] 200 - CACHED - https://files.pythonhosted.org/packages/fe/ca/466766e20b767ddb9b9512025[423](https://github.com/pyscript/pyscript/actions/runs/3931249013/jobs/6722258055#step:10:424)10cba37ea5f2d792dae7589f1741af58/urllib3-1.26.14-py2.py3-none-any.whl
[ 69.47 request         ] 200 - CACHED - https://files.pythonhosted.org/packages/fc/34/3030de6f1370931b9dbb4dad48f6ab1015ab1d32447850b9fc94e60097be/idna-3.4-py3-none-any.whl
[ 69.55 console.log     ] distutils already loaded from default channel
[ 69.55 console.log     ] pyparsing already loaded from default channel
[ 69.55 console.log     ] packaging already loaded from default channel
[ 69.55 console.log     ] Loading bokeh, numpy, jinja2, markupsafe, pillow, python-dateutil, six, typing-extensions, pyyaml, pandas, pytz, setuptools, tqdm, bleach, webencodings, certifi
[ 70.55 request         ] 200 - CACHED - https://cdn.jsdelivr.net/pyodide/v0.21.3/full/bokeh-2.4.3-py3-none-any.whl
[ 70.95 request         ] 200 - CACHED - https://cdn.jsdelivr.net/pyodide/v0.21.3/full/numpy-1.22.4-cp310-cp310-emscripten_3_1_14_wasm32.whl
[ 70.98 request         ] 200 - CACHED - https://cdn.jsdelivr.net/pyodide/v0.21.3/full/Jinja2-3.1.2-py3-none-any.whl
[ 70.99 request         ] 200 - CACHED - https://cdn.jsdelivr.net/pyodide/v0.21.3/full/MarkupSafe-2.1.1-cp310-cp310-emscripten_3_1_14_wasm32.whl
[ 71.04 request         ] 200 - CACHED - https://cdn.jsdelivr.net/pyodide/v0.21.3/full/PIL-9.1.1-cp310-cp310-emscripten_3_1_14_wasm32.whl
[ 71.07 request         ] 200 - CACHED - https://cdn.jsdelivr.net/pyodide/v0.21.3/full/python_dateutil-2.8.2-py2.py3-none-any.whl
[ 71.09 request         ] 200 - CACHED - https://cdn.jsdelivr.net/pyodide/v0.21.3/full/six-1.16.0-py2.py3-none-any.whl
[ 71.12 request         ] 200 - CACHED - https://cdn.jsdelivr.net/pyodide/v0.21.3/full/typing_extensions-4.2.0-py3-none-any.whl
[ 71.12 request         ] 200 - CACHED - https://cdn.jsdelivr.net/pyodide/v0.21.3/full/PyYAML-6.0-cp310-cp310-emscripten_3_1_14_wasm32.whl
[ 71.35 request         ] 200 - CACHED - https://cdn.jsdelivr.net/pyodide/v0.21.3/full/pandas-1.4.2-cp310-cp310-emscripten_3_1_14_wasm32.whl
[ 71.48 request         ] 200 - CACHED - https://cdn.jsdelivr.net/pyodide/v0.21.3/full/pytz-2022.1-py2.py3-none-any.whl
[ 71.57 request         ] 200 - CACHED - https://cdn.jsdelivr.net/pyodide/v0.21.3/full/setuptools-62.6.0-py3-none-any.whl
[ 71.58 request         ] 200 - CACHED - https://cdn.jsdelivr.net/pyodide/v0.21.3/full/tqdm-4.64.0-py2.py3-none-any.whl
[ 71.60 request         ] 200 - CACHED - https://cdn.jsdelivr.net/pyodide/v0.21.3/full/bleach-5.0.0-py3-none-any.whl
[ 71.60 request         ] 200 - CACHED - https://cdn.jsdelivr.net/pyodide/v0.21.3/full/webencodings-0.5.1-py2.py3-none-any.whl
[ 71.61 request         ] 200 - CACHED - https://cdn.jsdelivr.net/pyodide/v0.21.3/full/certifi-2022.6.15-py3-none-any.whl
[ 81.83 console.log     ] Loaded six, python-dateutil, typing-extensions, pytz, setuptools, tqdm, webencodings, bleach, certifi, markupsafe, jinja2, pyyaml, pillow, numpy, bokeh, pandas
[ 81.84 console.info    ] [pyscript/main] Paths to fetch:  []
[ 81.84 console.info    ] [pyscript/main] All paths fetched
[ 81.84 console.info    ] [pyscript/main] Plugins to fetch:  [../build/plugins/python/py_tutor.py]
[ 81.84 console.info    ] [pyscript/main]   fetching plugins: ../build/plugins/python/py_tutor.py
[ 81.84 request         ] 200 - fake_server - http://fake_server/build/plugins/python/py_tutor.py
[ 81.85 console.log     ] importing py_tutor
[ 81.86 console.warning ] WARNING: This plugin is still in a very experimental phase and will likely change and potentially break in the future releases. Use it with caution.
[ 81.86 console.info    ] Defining new custom element py-tutor
[ 81.86 console.info    ] [plugin] creating plugin: py-tutor
[ 81.86 console.debug   ] [plugin] creating py-tutor plugin instance
[ 81.87 console.info    ] Creating code introspection section.
[ 81.87 console.info    ] Module paths to parse: None
[ 81.87 console.info    ] Creating new code section element.
[ 81.88 request         ] 200 - fake_server - http://fake_server/examples/assets/prism/prism.css
[ 81.88 console.info    ] [pyscript/main] All plugins fetched
[ 81.88 console.info    ] [py-script] py-mount: found 0 elements
[ 81.88 console.info    ] [py-terminal] Registering stdio listener
[ 81.88 console.info    ] [pyscript/main] Executing <py-script> tags...
[ 81.89 request         ] 200 - fake_server - http://fake_server/examples/assets/prism/prism.js
[ 81.91 console.info    ] [pyscript/main] Initializing web components...
[ 81.91 console.debug   ] [py-script] Initializing py-* event handlers...
[ 81.91 console.info    ] [pyscript/main] Startup complete
[ 81.91 console.info    ] [py-splashscreen] Closing
[ 81.91 console.info    ] [pyscript/main] PyScript page fully initialized
[ 90.98 console.warning ] [bokeh] JS/Python version mismatch
[ 90.98 console.warning ] [bokeh] Library versions: JS (2.4.2) / Python (2.4.3)
[ 91.01 console.info    ] [bokeh] document idle at 12 ms
[ 91.03 console.log     ] /lib/python3.10/site-packages/pyodide/__init__.py:74: FutureWarning: pyodide.to_js has been moved to pyodide.ffi.to_js Accessing it through the pyodide module is deprecated.
[ 91.03 console.log     ]   warn(
[ 91.04 console.warning ] [bokeh] JS/Python version mismatch
[ 91.04 console.warning ] [bokeh] Library versions: JS (2.4.2) / Python (2.4.3)
[ 91.10 request         ] 200 - NETWORK - https://unpkg.com/tabulator-tables@4.9.3/dist/css/tabulator_simple.min.css
[ 91.15 console.info    ] [bokeh] document idle at 87 ms
[ 91.17 console.warning ] [bokeh] JS/Python version mismatch
[ 91.17 console.warning ] [bokeh] Library versions: JS (2.4.2) / Python (2.4.3)
[ 91.18 console.info    ] [bokeh] document idle at 9 ms
[ 91.27 console.js_error] ReferenceError: Tabulator is not defined
    at C.render (https://unpkg.com/@holoviz/panel@0.13.1/dist/panel.min.js:52:6005)
    at a.onload (https://unpkg.com/@holoviz/panel@0.13.1/dist/panel.min.js:52:15216)
=========================== short test summary info ============================
ERROR tests/integration/test_zz_examples.py::TestExamples::test_panel_stream[chromium]
======== 156 passed, 1 skipped, 3 xfailed, 1 error in [601](https://github.com/pyscript/pyscript/actions/runs/3931249013/jobs/6722258055#step:10:602).16s (0:10:01) ========
```

It's not clear why it started failing now, will dig a bit more.

**Comment by philippjfr** [comment]
Likely just a temporary unpkg outage:

```
playwright._impl._api_types.Error: Request timed out after 30000ms
=========================== logs ===========================
→ GET https://unpkg.com/tabulator-tables@4.9.3/dist/js/tabulator.js
```

**Comment by FabioRosado** [comment]
Oh right! Thanks haha

I lookedat the 200 response from the CSS itself, but missed the JS file completely 😬  

Locally, I tried to run the test 20 times with `pytest-repeat` and it passed all the time so I'll close the issue, thank you @philippjfr !
