### ISSUE TITLE
Just nothing works. for to inform the commuity

### ISSUE THREAD

**Issue by dimkiriakos** [pyscript/pyscript#1447]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

just copy and paste from your documentation https://docs.pyscript.net/latest/tutorials/requests.html#patching-the-requests-library and nothing works 
Good idea py-script but still looks like something theoretical. I have no time for more experimentation  
the error is that

Traceback (most recent call last):
  File "/lib/python3.10/_pyodide/_base.py", line 460, in eval_code
    .run(globals, locals)
  File "/lib/python3.10/_pyodide/_base.py", line 306, in run
    coroutine = eval(self.code, globals, locals)
  File "<exec>", line 5, in <module>
AttributeError: module 'pyodide_http' has no attribute 'patch'

if you are interested to make your project stable it's ok, if not just ignore it. I will continue with JavaScript in the front end. It's something more stable and works fine. When you will make something stable I will try it until then good luck

### Console info

```shell
Traceback (most recent call last):
  File "/lib/python3.10/_pyodide/_base.py", line 460, in eval_code
    .run(globals, locals)
  File "/lib/python3.10/_pyodide/_base.py", line 306, in run
    coroutine = eval(self.code, globals, locals)
  File "<exec>", line 5, in <module>
AttributeError: module 'pyodide_http' has no attribute 'patch'
```

### Additional Context

![image](https://user-images.githubusercontent.com/19278746/236155654-73092cd0-99ea-4988-b8c5-30bb7fc48178.png)

**Comment by WebReflection** [comment]
@dimkiriakos I think we have either a *typo* in the tutorial or the library changed method name. Using `patch_all()` instead of `patch()` works for me but while I think we should definitively fix those tutorials examples, errors in documentations happen with every software or programming language and it'd be great if we could all understand this and be a bit more relaxed around this topic, thanks.

**Comment by FabioRosado** [comment]
We also have the following guide which is a bit more advanced that explains how you can hit an API with different methods other than request, hope either the updated doc that @WebReflection  shared or this helps you https://docs.pyscript.net/latest/guides/http-requests.html 😄

**Comment by madhur-tandon** [comment]
This is a duplicate of https://github.com/pyscript/pyscript/issues/1291
Writing here so that we close both when we release the new docs.

**Comment by dimkiriakos** [comment]
> We also have the following guide which is a bit more advanced that explains how you can hit an API with different methods other than request, hope either the updated doc that @WebReflection shared or this helps you https://docs.pyscript.net/latest/guides/http-requests.html smile

Yes sure. However, if I want to try to learn something first I have to copy and paste the example to see if the code works. If not I will not spend even a minute more in my life for something that doesn't work. I'm not a college student. I've got a family

**Comment by WebReflection** [comment]
@dimkiriakos once again, you are simply witnessing a classic "*outdated documentation*" case, but you are adding some drama to it.

We have provided a few answers to help you forward and we agreed we should fix the documentation ASAP so ... thanks for filing the issue but I wonder why you filed such issue in the first place if there's no answer you want to hear.

Also please let's keep conversations calm and respectful, and this is the second time I need to mention that, thank you.
