### ISSUE TITLE
Can't use yt-dl , _ssl not found

### ISSUE THREAD

**Issue by Agono0** [pyscript/pyscript#162]
Here is the full error:
```Python

JsException(PythonError: Traceback (most recent call last): File "/lib/python3.10/site-packages/_pyodide/_base.py"
, line 429, in eval_code .run(globals, locals) File "/lib/python3.10/site-packages/_pyodide/_base.py"
, line 300, in run coroutine = eval(self.code, globals, locals) File ""
, line 1, in File "/lib/python3.10/site-packages/youtube_dl/__init__.py",
line 15, in from .options import ( File "/lib/python3.10/site-packages/youtube_dl/options.py", line 8, in from .downloader.external import list_external_downloaders File "/lib/python3.10/site-packages/youtube_dl/downloader/__init__.py"
, line 3, in from .common import FileDownloader File "/lib/python3.10/site-packages/youtube_dl/downloader/common.py"
, line 10, in from ..utils import ( File "/lib/python3.10/site-packages/youtube_dl/utils.py", 
line 30, in import ssl File "/lib/python3.10/ssl.py", line 98, in import _ssl # 
if we can't import it, let the error propagate ModuleNotFoundError: No module named '_ssl' )
```
When trying to use Youtube-dl

**Comment by verhulstm** [comment]
hi,

what you found might be related to this 

https://github.com/pyscript/pyscript/issues/91

**Comment by Agono0** [comment]
But I think ssl also not found....
Anyway thanks for info

**Comment by antocuni** [comment]
This seems related to this pyodide upstream issue: https://github.com/pyodide/pyodide/issues/529

**Comment by JoeyEamigh** [comment]
if you run `await micropip.install('ssl')` it works btw

**Comment by marimeireles** [comment]
Yes. It's a requests issue, you can try to workaround using https://docs.pyscript.net/latest/howtos/http-requests.html
Feel free to ask for help if you get stuck!
