### ISSUE TITLE
[RC1] `<script type="py" target...>` Fails

### ISSUE THREAD

**Issue by JeffersGlass** [pyscript/pyscript#1750]
Adding the `target` attribute to a `<script type="py">` tag causes an error:

```
script-handler.js:24 Uncaught (in promise) TypeError: r.getElementById is not a function
    at Et (script-handler.js:24:17)
    at onInterpreterReady (core.js:208:27)
```

This is caused by a signature mismatch in `queryTarget`. Will submit a PR.

**Comment by JeffersGlass** [comment]
I have read #1670 closely, and I _believe_ from what I read there that the intention is that the `target` attribute works on `<script type="py">` tags, hence this bug fix.

The `target` attribute of a `<py-script>` tag appears to do nothing; unclear to me in that's the desired behavior, but if it's not, that can be a separate issue.

**Comment by WebReflection** [comment]
I think in general `target` attribute is not supported (yet) but `target` has a very different meaning in *script* ... it returns the companion element once accessed and that element gets an ID. We have now `current_target()` Python API via `pyscript` module which is the one used by default with `display` ... if we add the `target` attribute there's likely more to change ... but I'll have a look at the PR.
