### ISSUE TITLE
pyscript not working inside shadow root

### ISSUE THREAD

**Issue by MarcSkovMadsen** [pyscript/pyscript#1820]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

I'm trying to use pyscript together with Panel and its `ReactiveHTML` component. The `ReactiveHTML` component enables me to write *custom components* for Panel.

I would like to write a PyScript/ Pyodide component that can take Python code from the server and run it in the client. I also wants to support more advanced use cases where everything is running in PyScript/ Pyodide.

But it does not work. To me it seems during the pyscript initialization it fails because th `py-script` tags are inside `shadow-root`.

```bash
pip install panel
```

```python
import panel as pn
import param
from panel.reactive import ReactiveHTML

pn.extension()

CODE = """
import panel as pn

pn.extension()

pn.panel("Hello World).servable()
"""

TEMPLATE = """
<div id="pn-container">
    <py-config>
        packages = [
            'https://cdn.holoviz.org/panel/wheels/bokeh-3.3.0-py3-none-any.whl',
            'https://cdn.holoviz.org/panel/1.3.0/dist/wheels/panel-1.3.0-py3-none-any.whl',
            'pyodide-http==0.2.1'
        ]       
    </py-config>
    <py-script id="pn-code">
    ${code}
    </py-script>
</div>
"""

class CustomComponent(ReactiveHTML):
    code = param.String(CODE)

    _template = TEMPLATE

    __javascript__=[
        "https://pyscript.net/releases/2023.03.1/pyscript.js",
        "https://cdn.bokeh.org/bokeh/release/bokeh-3.3.0.min.js",
        "https://cdn.bokeh.org/bokeh/release/bokeh-gl-3.3.0.min.js",
        "https://cdn.bokeh.org/bokeh/release/bokeh-widgets-3.3.0.min.js",
        "https://cdn.bokeh.org/bokeh/release/bokeh-tables-3.3.0.min.js",
        "https://cdn.holoviz.org/panel/1.3.0/dist/panel.min.js",
    ]

CustomComponent(width=500, height=200).servable()
```

```bash
panel serve script.py
```

![image](https://github.com/pyscript/pyscript/assets/42288570/66eb2f83-5f6e-45db-90f5-17da22a2923a)

### Console info

```shell
[pyexec] Python exception:
Traceback (most recent call last):
  File "/home/pyodide/pyscript/__init__.py", line 484, in uses_top_level_await
    return TopLevelAsyncFinder().is_source_top_level_await(source)
  File "/home/pyodide/pyscript/__init__.py", line 466, in is_source_top_level_await
    node = ast.parse(source)
  File "/lib/python3.10/ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 1
    <div class="bk-panel-models-markup-HTML markdown"></div>
    ^
SyntaxError: invalid syntax
```

**Comment by WebReflection** [comment]
which version of PyScript are you running?

**Comment by MarcSkovMadsen** [comment]
The one Panel is pointing to. With Panel 1.3.0 it is 2023.03.1.

**Comment by WebReflection** [comment]
not panel ... PyScript ... which pyscript URL are you using?

**Comment by MarcSkovMadsen** [comment]
`PYSCRIPT_JS = f'<script defer src="https://pyscript.net/releases/{PYSCRIPT_VERSION}/pyscript.js"></script>'` with `PYSCRIPT_VERSION=2023.03.1`.

**Comment by WebReflection** [comment]
we're out with PyScript next 2023.11.1 now, have you tried that?
