### ISSUE TITLE
[2023.11.01_RC3] Uncaught error // inconsistent behaviour when instantiating Terminal in both worker and main thread

### ISSUE THREAD

**Issue by leriomaggio** [pyscript/pyscript#1834]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

Release: `2023.11.01_RC3`

**Scenario**
Using the new `terminal` attribute in two separate `<script type="py">` tags within the same app. 
In one case / tag  the terminal is spawned into a web worker, whilst the second script spawns the terminal in the main thread. 

Different behaviours occur depending on the **order** these two tags are used within the app. 

**Case 1**: Worker + Main

```html
<!-- worker -->
<script type="py" terminal worker>print("Hello worker")</script>
<!-- main -->
<script type="py" terminal>
    print(f"Hello Main")
</script>
```

**Outcome**:
* `Hello worker` is shown;
* Terminal **is** interactive
* `Hello Main` shown **only** in the console (_as I suppose it is a different terminal instance ?_).

**Case 2** : Main + Worker

```html
<!-- main -->
<script type="py" terminal>
    print(f"Hello Main")
</script>
<!-- worker -->
<script type="py" terminal worker>print("Hello worker")</script>
```
**Outcome**:
* `Hello Main` is shown;
* `Hello worker` is showed **only** in the console 
* There is no interactive terminal.

**Case 2.5**: Main + Worker (using `input`)

```html
<script type="py" terminal>
            print(f"Hello Main")
</script>
<script type="py" terminal worker>
    name = input("What is your name ?")
    print("hello {name}")
</script>
```

**Outcome**:
* `Hello Main` is shown;
* Uncaught Exception in worker:
```python
pyodide.asm.js:9 ReferenceError: prompt is not defined
    at Object.stdin (pyodide.asm.js:9:114646)
    at Ue._getInput (pyodide.asm.js:9:116326)
    at Ue.read (pyodide.asm.js:9:116896)
    at pyodide.asm.js:9:113857
    at handleEAGAIN (pyodide.asm.js:9:112987)
    at readWriteHelper (pyodide.asm.js:9:113103)
    at Object.read (pyodide.asm.js:9:113839)
    at Object.read (pyodide.asm.js:9:217843)
    at doReadv (pyodide.asm.js:9:357908)
    at _fd_read (pyodide.asm.js:9:359187)

588d39ce-7238-47a0-9159-8a931c24719d:2 PythonError: Traceback (most recent call last):
  File "/lib/python311.zip/_pyodide/_base.py", line 499, in eval_code
    .run(globals, locals)
     ^^^^^^^^^^^^^^^^^^^^
  File "/lib/python311.zip/_pyodide/_base.py", line 340, in run
    coroutine = eval(self.code, globals, locals)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<exec>", line 28, in <module>
OSError: [Errno 29] I/O error
```

**Take aways**:

- user experience should be different, imho: the presence of two different terminals gets uncaught / unhandled.
- In case 2.5 there is an exception to catch, I think :) 

HTH

### What browsers are you seeing the problem on? (if applicable)

Chrome

### Additional Context

Testing this on PSDC

**Comment by WebReflection** [comment]
we support only one terminal per page at the moment, so the resolution is to throw an error if more than one exists ... would that work?

**Comment by leriomaggio** [comment]
Yeah! I think that one terminal per page is more than fair! What I was more concerned about was the lack of info to the end user of this "restriction" - plus I/O error should be handled :)

**Comment by WebReflection** [comment]
the errors in workers are not handled the same as in main but the bootstrap happens in main and it should throw already ... maybe what you'd expect is that worker code shouldn't even try to run if the main threw an error, but this is for a wider discussion around errors between workers and main as workers know nothing and we don't want to leak any detail in main neither ... workers can forward errors to main but we don't leak all workers neither so we can't do the other way around.

**Comment by WebReflection** [comment]
on the other hand, I can try to intercept missing `sync` helpers for the worker before executing the code but then again, the worker has a hook for `codeAfterRun` that bootstrap the better terminal ... so here the summary:

  * on *main*, the terminal is read only for the user ... no interaction possible
  * on *worker*, the terminal is 100% a terminal
  * the two cannot coexist but arguably we might want to forward main code to the worker when one terminal there exists (TBD)
  * multiple `py-script` were never fully supported in classic and next doesn't try to do much more
  * worker never existed in classic (as release) so this is all new territory to explore to me, expectations might be very subjective and having multiple scripts is not, or has never really been, the way users actually code ... workers exist to avoid blocking the main thread, having both workers and main means twice the time to bootstrap pyodide and that should be really discouraged

Last, but not least, as workers don't know anything about other workers, multiple workers that land on the same worker terminal is a whole new world of shenanigans to solve and it was never discussed to date.

**Comment by WebReflection** [comment]
maybe it's also worth writing down that *py-terminal* is not a substitute for the repl ... we don't support *classic repl* use cases yet, it's still in the making and it will also probably change name (cell) which I like as it drops some confusion.

A terminal is a single terminal that handle output on main or it's interactive in worker for both input and output ... that's all it does and I am personally not sure it should do more.

**Comment by WebReflection** [comment]
AFAIK the code should throw already so there's clearly something wrong with it because I wouldn't expect multiple terminals to ever be possible at all (and no terminal should bootstrap neither) ... looking into it as we speak.

**Comment by WebReflection** [comment]
@antocuni OK, there is a console warning, but it doesn't throw an error ... it looks like we went too lightweight in informing a single terminal should be on the page because as you mentioned multiple times, "*regular users don't read the console*" ... I guess this is clearly one of those cases ... I am happy to translate that `console.warn` into an *Error* and close this, but I would like to understand if this other issue is agreed so that I don't need to work twice on the same thing, as here I would throw, and there I would throw only in different scenarios: https://github.com/pyscript/pyscript/issues/1835#issuecomment-1791053797

**Comment by antocuni** [comment]
> @antocuni OK, there is a console warning, but it doesn't throw an error ... it looks like we went too lightweight in informing a single terminal should be on the page because as you mentioned multiple times, "_regular users don't read the console_" ... I guess this is clearly one of those cases ... I am happy to translate that `console.warn` into an _Error_ and close this, but I would like to understand if this other issue is agreed so that I don't need to work twice on the same thing, as here I would throw, and there I would throw only in different scenarios: [#1835 (comment)](https://github.com/pyscript/pyscript/issues/1835#issuecomment-1791053797)

I think that it's fine to keep it as a warning, but all our warnings should go to (also) the DOM, not just to the console.
That's how things worked in classic

**Comment by WebReflection** [comment]
it currently throws with more than a terminal
