### ISSUE TITLE
SerpWow API project issue

### ISSUE THREAD

**Issue by i6y** [pyscript/pyscript#1856]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

(Python code in additional info) I'm trying to make my code, which uses a search engine API to return Wikipedia results from a Google search from user-input code in a readable form, in a web-page format by using pyscript. I want my project to end up a research helper, grabbing results from many trusted sources like Britannica and history.com. However, after tons of different versions and attempts, I find the most successful one having an issue with HTTP requests. Sorry for my bad writing, my brain is fried after two essays today, and a paper last evening.
(This code works alone when ran locally, but upon using it with pyscript, the error occurs.)
Let me know if you need the full HTML code and config JSON.

### What browsers are you seeing the problem on? (if applicable)

Chrome, Other

### Console info

```shell
JsException(PythonError: Traceback (most recent call last): File "/lib/python3.10/site-packages/urllib3/connection.py", line 203, in _new_conn sock = connection.create_connection( File "/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection raise err File "/lib/python3.10/site-packages/urllib3/util/connection.py", line 67, in create_connection _set_socket_options(sock, socket_options) File "/lib/python3.10/site-packages/urllib3/util/connection.py", line 100, in _set_socket_options sock.setsockopt(*opt) OSError: [Errno 50] Protocol not available The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/lib/python3.10/site-packages/urllib3/connectionpool.py", line 790, in urlopen response = self._make_request( File "/lib/python3.10/site-packages/urllib3/connectionpool.py", line 491, in _make_request raise new_e File "/lib/python3.10/site-packages/urllib3/connectionpool.py", line 467, in _make_request self._validate_conn(conn) File "/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1096, in _validate_conn conn.connect() File "/lib/python3.10/site-packages/urllib3/connection.py", line 611, in connect self.sock = sock = self._new_conn() File "/lib/python3.10/site-packages/urllib3/connection.py", line 218, in _new_conn raise NewConnectionError( urllib3.exceptions.NewConnectionError: : Failed to establish a new connection: [Errno 50] Protocol not available The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/lib/python3.10/site-packages/requests/adapters.py", line 486, in send resp = conn.urlopen( File "/lib/python3.10/site-packages/urllib3/connectionpool.py", line 844, in urlopen retries = retries.increment( File "/lib/python3.10/site-packages/urllib3/util/retry.py", line 515, in increment raise MaxRetryError(_pool, url, reason) from reason # type: ignore[arg-type] urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.serpwow.com', port=443): Max retries exceeded with url: /search?q=memes&num=100&api_key=7F3C0B8A20E34F588F539E056F861C08 (Caused by NewConnectionError(': Failed to establish a new connection: [Errno 50] Protocol not available')) During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/lib/python3.10/site-packages/_pyodide/_base.py", line 429, in eval_code .run(globals, locals) File "/lib/python3.10/site-packages/_pyodide/_base.py", line 300, in run coroutine = eval(self.code, globals, locals) File "", line 19, in File "/lib/python3.10/site-packages/requests/api.py", line 73, in get return request("get", url, params=params, **kwargs) File "/lib/python3.10/site-packages/requests/api.py", line 59, in request return session.request(method=method, url=url, **kwargs) File "/lib/python3.10/site-packages/requests/sessions.py", line 589, in request resp = self.send(prep, **send_kwargs) File "/lib/python3.10/site-packages/requests/sessions.py", line 703, in send r = adapter.send(request, **kwargs) File "/lib/python3.10/site-packages/requests/adapters.py", line 519, in send raise ConnectionError(e, request=request) requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.serpwow.com', port=443): Max retries exceeded with url: /search?q=memes&num=100&api_key=################ (Caused by NewConnectionError(': Failed to establish a new connection: [Errno 50] Protocol not available')) )
```

### Additional Context

Python code removed for site format issues

**Comment by JeffersGlass** [comment]
The HTML and Python code will likely be necessary for us to fully help you... but from your error message, I'm guessing you're using the `requests` package, which doesn't work out-of-the-box in PyScript/Pyodide. However, you can patch it using the [pyodide-http](https://github.com/koenvo/pyodide-http) package, which sometimes yields success.

If you're having code formatting issues here, try putting your code inside a [fenced code block](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) like this:
````
```html
<p> Hello world! </p>
```
````
or 
````
```py
def foo():
    print("FOO!")
```
````

**Comment by i6y** [comment]
Here's the full HTML code:
```
<!DOCTYPE html>
<html>
  <head>
      <meta charset="utf-8" />
      <meta name="viewport" content="width=device-width,initial-scale=1" />
      <title>Research Helper</title>
      <script type="module" src="https://pyscript.net/releases/2023.11.1/core.js"></script>
  </head>
  <body>
    <h1>Polyglot 🦜 💬 🇬🇧 ➡️ 🏴‍☠️</h1>
    <p>Translate English into Pirate speak...</p>
    <input type="text" id="english" placeholder="Type English here..." />
    <button py-click="main">foooooooo baaaaaaarr.....</button>
    <div id="output"></div>
    <script type="py" src="./main.py" config="./pyscript.json"></script>
  </body>
</html>
```
..and the Python code:
```
import requests
# Prompt user to input number of results desired and assert default if left blank
q = input("Search topic?\n    ")
num = input("How many results? default is 100\n    ")
if num == "":
    num = "100"

# Search parameters where "q" is the search key-phrase,
# "num" is the desired amount of search results,
# "api_key" is, well, the api key
params = {
    'q': q,
    'num': num,
    'api_key': '7F3C0B8A20E34F588F539E056F861C08'
}
# Creating search variable
apiResult = requests.get('https://api.serpwow.com/search', params)
results = apiResult.json()
# Assigns dict of json result to results
# Creates variable for organic results section of results dictionary
organicResults = results["organic_results"]
# Wikipedia element search
print("Wikipedia results on google:")
for i in range(organicResults.index(organicResults[-1]) + 1):
    if "wikipedia" in organicResults[i]["link"]:
        print("    \"" + organicResults[i]["title"] + "\"")
        print("    \"" + organicResults[i]["link"] + "\"")
```

**Comment by i6y** [comment]
Update: I implemented pyodide-http and now the only problem i get which prevents the code from running is this:
`error.js:15 PythonError: Traceback (most recent call last):
  File "/lib/python311.zip/_pyodide/_base.py", line 499, in eval_code
    .run(globals, locals)
     ^^^^^^^^^^^^^^^^^^^^
  File "/lib/python311.zip/_pyodide/_base.py", line 340, in run
    coroutine = eval(self.code, globals, locals)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<exec>", line 37, in <module>
OSError: [Errno 29] I/O error

    at new_error (pyodide.asm.js:9:12519)
    at pyodide.asm.wasm:0x158827
    at pyodide.asm.wasm:0x15892c
    at Module._pythonexc2js (pyodide.asm.js:9:640895)
    at Module.callPyObjectKwargs (pyodide.asm.js:9:81856)
    at Proxy.callKwargs (pyodide.asm.js:9:97507)
    at Object.runPython (pyodide.asm.js:9:118859)
    at Object.pt [as run] (_python.js:12:28)
    at e.<computed> (utils.js:61:9)
    at Ct.e.<computed> [as run] (hooks.js:65:39)
    at Object.run (utils.js:53:36)
    at Object.onReady (core.js:183:64)`

**Comment by Neon22** [comment]
If you add a terminal you might get better error reporting.
```<script type="module" src="https://pyscript.net/releases/2023.11.1/core.js"></script>```
```<script type="module" src="https://pyscript.net/releases/2023.11.1/core.js" terminal></script>```

**Comment by i6y** [comment]
i just added the "terminal" attribute to that, but it still shows the same error:
```
pyodide.asm.js:9 TypeError: Illegal invocation
    at Ue._getInput (pyodide.asm.js:9:116326)
    at Ue.read (pyodide.asm.js:9:116896)
    at pyodide.asm.js:9:113857
    at handleEAGAIN (pyodide.asm.js:9:112987)
    at readWriteHelper (pyodide.asm.js:9:113103)
    at Object.read (pyodide.asm.js:9:113839)
    at Object.read (pyodide.asm.js:9:217843)
    at doReadv (pyodide.asm.js:9:357908)
    at _fd_read (pyodide.asm.js:9:359187)
    at pyodide.asm.wasm:0x444dd3


error.js:15 PythonError: Traceback (most recent call last):
  File "/lib/python311.zip/_pyodide/_base.py", line 499, in eval_code
    .run(globals, locals)
     ^^^^^^^^^^^^^^^^^^^^
  File "/lib/python311.zip/_pyodide/_base.py", line 340, in run
    coroutine = eval(self.code, globals, locals)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<exec>", line 37, in <module>
OSError: [Errno 29] I/O error

    at new_error (pyodide.asm.js:9:12519)
    at pyodide.asm.wasm:0x158827
    at pyodide.asm.wasm:0x15892c
    at Module._pythonexc2js (pyodide.asm.js:9:640895)
    at Module.callPyObjectKwargs (pyodide.asm.js:9:81856)
    at Proxy.callKwargs (pyodide.asm.js:9:97507)
    at Object.runPython (pyodide.asm.js:9:118859)
    at Object.pt [as run] (_python.js:12:28)
    at e.<computed> (utils.js:61:9)
    at Ct.e.<computed> [as run] (hooks.js:65:39)
    at Object.run (utils.js:53:36)
    at Object.onReady (core.js:183:64)
```

**Comment by i6y** [comment]
im just scrapping this and rewriting it all in javascript i have to present tomorrow anyways
