### ISSUE TITLE
MicroPython doesn't support pydom (warnings module not found)

### ISSUE THREAD

**Issue by kkinder** [pyscript/pyscript#1895]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

It seems that when you try to use pydom with the Micropython implementation, it doesn't work because Micropython doesn't have a warnings module. Here are some steps to recreate the issue:

Create a simple html file:

```
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width,initial-scale=1"/>
  <title>Test</title>
  <link rel="stylesheet" href="https://pyscript.net/releases/2023.11.2/core.css">
  <script type="module" src="https://pyscript.net/releases/2023.11.2/core.js"></script>
</head>
<body>
<mpy-config></mpy-config>
<mpy-script>
from pyweb import pydom
</mpy-script>
</body>
</html>
```

You'll get this exception.

```error.js:15 PythonError: Traceback (most recent call last):
  File "<stdin>", line 40, in <module>
  File "pyweb/pydom.py", line 2, in <module>
ImportError: no module named 'warnings'

    at convert_mp_to_js_obj_jsside (micropython.mjs:5120:15)
    at convert_mp_to_js_obj_jsside_with_free (micropython.mjs:5161:17)
    at Object.runPython (micropython.mjs:5005:20)
    at Object.bt [as run] (_python.js:12:28)
    at e.<computed> (utils.js:61:9)
    at e.<computed> [as run] (hooks.js:65:39)
    at run (utils.js:53:36)
    at HTMLElement.connectedCallback (core.js:301:55)```



### What browsers are you seeing the problem on? (if applicable)

Chrome, Safari

### Console info

```shell
error.js:15 Traceback (most recent call last):
e.main.onReady.add.r.io.stderr @ error.js:15
stderr @ _utils.js:16
Module.stderr @ micropython.mjs:4972
write @ micropython.mjs:3215
write @ micropython.mjs:2837
doWritev @ micropython.mjs:3960
_fd_write @ micropython.mjs:3974
$func1396 @ micropython.wasm:0x3d7b8
$func1248 @ micropython.wasm:0x35fd2
$func114 @ micropython.wasm:0x36fa
$func439 @ micropython.wasm:0x13440
$func1238 @ micropython.wasm:0x3511b
invoke_vii @ micropython.mjs:4491
$mp_js_do_exec @ micropython.wasm:0x344d1
(anonymous) @ micropython.mjs:720
ccall @ micropython.mjs:4089
runPython @ micropython.mjs:5004
bt @ _python.js:12
e.<computed> @ utils.js:61
e.<computed> @ hooks.js:65
run @ utils.js:53
connectedCallback @ core.js:301
await in connectedCallback (async)
(anonymous) @ core.js:268
Promise.then (async)
(anonymous) @ core.js:127
error.js:15   File "<stdin>", line 40, in <module>
e.main.onReady.add.r.io.stderr @ error.js:15
stderr @ _utils.js:16
Module.stderr @ micropython.mjs:4972
write @ micropython.mjs:3215
write @ micropython.mjs:2837
doWritev @ micropython.mjs:3960
_fd_write @ micropython.mjs:3974
$func1396 @ micropython.wasm:0x3d7b8
$func1248 @ micropython.wasm:0x35fd2
$func119 @ micropython.wasm:0x3d53
$func118 @ micropython.wasm:0x3ce7
$func439 @ micropython.wasm:0x134c5
$func1238 @ micropython.wasm:0x3511b
invoke_vii @ micropython.mjs:4491
$mp_js_do_exec @ micropython.wasm:0x344d1
(anonymous) @ micropython.mjs:720
ccall @ micropython.mjs:4089
runPython @ micropython.mjs:5004
bt @ _python.js:12
e.<computed> @ utils.js:61
e.<computed> @ hooks.js:65
run @ utils.js:53
connectedCallback @ core.js:301
await in connectedCallback (async)
(anonymous) @ core.js:268
Promise.then (async)
(anonymous) @ core.js:127
error.js:15   File "pyweb/pydom.py", line 2, in <module>
e.main.onReady.add.r.io.stderr @ error.js:15
stderr @ _utils.js:16
Module.stderr @ micropython.mjs:4972
write @ micropython.mjs:3215
write @ micropython.mjs:2837
doWritev @ micropython.mjs:3960
_fd_write @ micropython.mjs:3974
$func1396 @ micropython.wasm:0x3d7b8
$func1248 @ micropython.wasm:0x35fd2
$func119 @ micropython.wasm:0x3d53
$func118 @ micropython.wasm:0x3ce7
$func439 @ micropython.wasm:0x134c5
$func1238 @ micropython.wasm:0x3511b
invoke_vii @ micropython.mjs:4491
$mp_js_do_exec @ micropython.wasm:0x344d1
(anonymous) @ micropython.mjs:720
ccall @ micropython.mjs:4089
runPython @ micropython.mjs:5004
bt @ _python.js:12
e.<computed> @ utils.js:61
e.<computed> @ hooks.js:65
run @ utils.js:53
connectedCallback @ core.js:301
await in connectedCallback (async)
(anonymous) @ core.js:268
Promise.then (async)
(anonymous) @ core.js:127
error.js:15 ImportError: no module named 'warnings'
e.main.onReady.add.r.io.stderr @ error.js:15
stderr @ _utils.js:16
Module.stderr @ micropython.mjs:4972
write @ micropython.mjs:3215
write @ micropython.mjs:2837
doWritev @ micropython.mjs:3960
_fd_write @ micropython.mjs:3974
$func1396 @ micropython.wasm:0x3d7b8
$func1248 @ micropython.wasm:0x35fd2
$func114 @ micropython.wasm:0x36fa
$func439 @ micropython.wasm:0x134ec
$func1238 @ micropython.wasm:0x3511b
invoke_vii @ micropython.mjs:4491
$mp_js_do_exec @ micropython.wasm:0x344d1
(anonymous) @ micropython.mjs:720
ccall @ micropython.mjs:4089
runPython @ micropython.mjs:5004
bt @ _python.js:12
e.<computed> @ utils.js:61
e.<computed> @ hooks.js:65
run @ utils.js:53
connectedCallback @ core.js:301
await in connectedCallback (async)
(anonymous) @ core.js:268
Promise.then (async)
(anonymous) @ core.js:127
micropython.mjs:5119 MicroPython exception: Traceback (most recent call last):
  File "<stdin>", line 40, in <module>
  File "pyweb/pydom.py", line 2, in <module>
ImportError: no module named 'warnings'

convert_mp_to_js_obj_jsside @ micropython.mjs:5119
convert_mp_to_js_obj_jsside_with_free @ micropython.mjs:5161
runPython @ micropython.mjs:5005
bt @ _python.js:12
e.<computed> @ utils.js:61
e.<computed> @ hooks.js:65
run @ utils.js:53
connectedCallback @ core.js:301
await in connectedCallback (async)
(anonymous) @ core.js:268
Promise.then (async)
(anonymous) @ core.js:127
error.js:15 PythonError: Traceback (most recent call last):
  File "<stdin>", line 40, in <module>
  File "pyweb/pydom.py", line 2, in <module>
ImportError: no module named 'warnings'

    at convert_mp_to_js_obj_jsside (micropython.mjs:5120:15)
    at convert_mp_to_js_obj_jsside_with_free (micropython.mjs:5161:17)
    at Object.runPython (micropython.mjs:5005:20)
    at Object.bt [as run] (_python.js:12:28)
    at e.<computed> (utils.js:61:9)
    at e.<computed> [as run] (hooks.js:65:39)
    at run (utils.js:53:36)
    at HTMLElement.connectedCallback (core.js:301:55)
e.main.onReady.add.r.io.stderr @ error.js:15
bt @ _python.js:15
e.<computed> @ utils.js:61
e.<computed> @ hooks.js:65
run @ utils.js:53
connectedCallback @ core.js:301
await in connectedCallback (async)
(anonymous) @ core.js:268
Promise.then (async)
(anonymous) @ core.js:127
```

**Comment by SarthakNikhal** [comment]
Can I work on this issue if it is still active?
