### ISSUE TITLE
MicroPython should provide better error messages for missing APIs

### ISSUE THREAD

**Issue by laffra** [pyscript/pyscript#1959]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

I run my app on PyScript 2024.1.[1 or 2], with MicroPython, and see a cryptic error occur. This does not happen on 2023.11.2. The error is not attached to any Python stacks. It also does not mention what API is missing. 

![mpy error message](https://github.com/pyscript/pyscript/assets/20541480/9285bbac-5539-4eea-b70b-dd673a4c1e46)

**Comment by fpliger** [comment]
Agree on the overall sentiment (MicroPython error messages needing more clarity)

In the meantime, @laffra do you have a code sample that we can use to reproduce?

**Comment by laffra** [comment]
I have no easy code sample. I have no idea when this code path is executed
in my complex application that appears to behave normally otherwise....

**Comment by WebReflection** [comment]
This is **not a solution** rather a possible workaround to at least understand what kind of object passes through that proxy trap and what is the property name that is accessing it.

This `<script>` should be **the very first script on the page** so on top of the `<head>` or surely before any PyScript code gets a chance to execute.

```html
<script>
($Proxy => {
  globalThis.Proxy = class Proxy {
    constructor(target, handler) {
      const { has } = handler;
      handler.has = (target, name) => {
        console.warn(`has("${name}") for`, target);
        return has?.call(handler, target, name);
      };
    }
  }
})(Proxy);
</script>
```

We are rather after [a rewrite of the MicroPython Proxy](https://gist.github.com/WebReflection/51e54ff1aa7264aaaddda49edac9977b) and I believe "*better errors*" will be inherently part of the refactoring as currently we have an explicit `throw new Error('not implemented')` in various proxies traps so tha as soon as any JS tries to understand the shape of a Python object that miserably (currently) fails in MicroPython (only).

**Comment by laffra** [comment]
I tried your patch, but if I use it, my page does not load at with the
following error message:
```
loader.js:56 Uncaught (in promise) TypeError: et is not a function
    at sn (loader.js:56:12)
    at jn (script-handler.js:89:26)
    at $n (custom.js:77:66)
    at Array.forEach (<anonymous>)
    at define (custom.js:242:29)
    at core.js:260:13
```

**Comment by laffra** [comment]
That prints the following:
```
micropython.mjs:4805 Uncaught Error: convert_js_to_mp_obj_jsside: not
implemented
    at convert_js_to_mp_obj_jsside (micropython.mjs:5512:15)
    at proxy_call_python (micropython.mjs:5370:13)
    at console.obj [as warn] (micropython.mjs:5570:24)
    at Proxy.handler.has (?U=zvaUM3ngRitJN1V4KRKx:10:27)
    at convert_js_to_mp_obj_jsside (micropython.mjs:5510:53)
    at call1 (micropython.mjs:998:132)
    at micropython.wasm:0x360bf
    at micropython.wasm:0x11333
    at micropython.wasm:0x11389
    at invoke_iii (micropython.mjs:4802:36)
```

**Comment by WebReflection** [comment]
Yes, the snippet won't remove the error as that's not possible (as it's backed in MicroPython) but you should read something in console (devtools) ... and by something I mean a warning ... don't you have any warning in console that prints `has("...") for` anywhere? It's very hard to help further without having a reproducible project to test against though, apologies if my help is actually not helping much.

**Comment by WebReflection** [comment]
This has been fixed in latest MicroPython so this error should not come up anymore.
