### ISSUE TITLE
Help with building a briefcase project for the web

### ISSUE THREAD

**Issue by fossie08** [pyscript/pyscript#2020]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

I am trying to get an app that I have written for an android device in toga using briefcase to build for the web. I am running into this issue when I run `briefcase run web`

(PY1001): Unable to install package(s) '/static/wheels/certifi-2024.2.2-py3-none-any.whl, /static/wheels/charset_normalizer-3.3.2-cp311-cp311-win_amd64.whl, /static/wheels/idna-3.6-py3-none-any.whl, /static/wheels/keepertimeclient-0.0.1-py3-none-any.whl, /static/wheels/requests-2.31.0-py3-none-any.whl, /static/wheels/toga_core-0.4.2-py3-none-any.whl, /static/wheels/toga_web-0.4.2-py3-none-any.whl, /static/wheels/travertino-0.3.0-py3-none-any.whl, /static/wheels/urllib3-2.2.1-py3-none-any.whl'. Reason: Traceback (most recent call last): File "/lib/python3.11/site-packages/micropip/_micropip.py", line 576, in install await transaction.gather_requirements(requirements) File "/lib/python3.11/site-packages/micropip/_micropip.py", line 342, in gather_requirements await gather(*requirement_promises) File "/lib/python3.11/site-packages/micropip/_micropip.py", line 353, in add_requirement wheel.check_compatible() File "/lib/python3.11/site-packages/micropip/_micropip.py", line 118, in check_compatible raise ValueError( ValueError: Wheel platform 'win_amd64' is not compatible with Pyodide's platform 'emscripten-3.1.32-wasm32' . Please open an issue at https://github.com/pyscript/pyscript/issues/new if you require help or you think it's a bug.

### What browsers are you seeing the problem on? (if applicable)

Chrome

### Console info

```shell
[pyscript/pyodide] PythonError: Traceback (most recent call last):
  File "/lib/python3.11/site-packages/micropip/_micropip.py", line 576, in install
    await transaction.gather_requirements(requirements)
  File "/lib/python3.11/site-packages/micropip/_micropip.py", line 342, in gather_requirements
    await gather(*requirement_promises)
  File "/lib/python3.11/site-packages/micropip/_micropip.py", line 353, in add_requirement
    wheel.check_compatible()
  File "/lib/python3.11/site-packages/micropip/_micropip.py", line 118, in check_compatible
    raise ValueError(
ValueError: Wheel platform 'win_amd64' is not compatible with Pyodide's platform 'emscripten-3.1.32-wasm32'


exceptions.ts:62 (PY1001): Unable to install package(s) '/static/wheels/certifi-2024.2.2-py3-none-any.whl, /static/wheels/charset_normalizer-3.3.2-cp311-cp311-win_amd64.whl, /static/wheels/idna-3.6-py3-none-any.whl, /static/wheels/ifaddr-0.2.0-py3-none-any.whl, /static/wheels/keepertimeclient-0.0.1-py3-none-any.whl, /static/wheels/requests-2.31.0-py3-none-any.whl, /static/wheels/toga_core-0.4.2-py3-none-any.whl, /static/wheels/toga_web-0.4.2-py3-none-any.whl, /static/wheels/travertino-0.3.0-py3-none-any.whl, /static/wheels/urllib3-2.2.1-py3-none-any.whl, /static/wheels/zeroconf-0.132.0-cp311-cp311-win_amd64.whl'. Reason: Traceback (most recent call last):
  File "/lib/python3.11/site-packages/micropip/_micropip.py", line 576, in install
    await transaction.gather_requirements(requirements)
  File "/lib/python3.11/site-packages/micropip/_micropip.py", line 342, in gather_requirements
    await gather(*requirement_promises)
  File "/lib/python3.11/site-packages/micropip/_micropip.py", line 353, in add_requirement
    wheel.check_compatible()
  File "/lib/python3.11/site-packages/micropip/_micropip.py", line 118, in check_compatible
    raise ValueError(
ValueError: Wheel platform 'win_amd64' is not compatible with Pyodide's platform 'emscripten-3.1.32-wasm32'
. Please open an issue at https://github.com/pyscript/pyscript/issues/new if you require help or you think it's a bug.
```

### Additional Context

I've had a look and my system is running x64 with python version 3.11.9

**Comment by WebReflection** [comment]
can we have a look at your TOML  file?

**Comment by WebReflection** [comment]
it also looks to me you downloaded pyodide but not the version with all its packages ... which is huge ... have you tried to download locally instead (or deploy) a pyodide that includes also all wheels? this feels like an offline-like use case and all caveats around are relevant ... see https://pyscript.github.io/docs/2024.1.3/user-guide/offline/

**Comment by WebReflection** [comment]
in particular: https://pyscript.github.io/docs/2024.1.3/user-guide/offline/#local-pyodide

I am closing this as it looks like a setup issue, not a project one. Feel free to ask more or providew more details to make it a project issue, thanks!
