### ISSUE TITLE
pyscript script link not working ...

### ISSUE THREAD

**Issue by rahim0004** [pyscript/pyscript#251]
I just wanted to experience pyscript for the first time by simply printing 'hellow, world!", But it look like pyscript is not working. It is giving me errors.

**_### My Code:_**
```
<html>
<head>
    <link rel="stylesheet" href="https://pyscript.net/alpha/pyscript.css"/>
    <script defer src="https://pyscript.net/alpha/pyscript.js"></script>
</head>

<body>
    <py-script>
        print("hello, world!")
    </py-script>
</body>
</html>
```

**_### Getting This Error :_**

`JsException(PythonError: Traceback (most recent call last): File "/lib/python3.10/site-packages/_pyodide/_base.py", line 421, in eval_code CodeRunner( File "/lib/python3.10/site-packages/_pyodide/_base.py", line 237, in __init__ self.ast = next(self._gen) File "/lib/python3.10/site-packages/_pyodide/_base.py", line 141, in _parse_and_compile_gen mod = compile(source, filename, mode, flags | ast.PyCF_ONLY_AST) File "", line 2 def wallis(n): IndentationError: unexpected indent )`

**Comment by aovasylenko** [comment]
@rahim0004 what browser are you using? Your example works for me

**Comment by jaynarayan-vaishnav** [comment]
It's mentioned in the README.md file.
```PyScript has been only tested on Chrome, at the moment.```
Maybe that's the issue if you are using a different browser. @rahim0004

**Comment by rahim0004** [comment]
> The code in question should follow Python indentation:
> 
> ```
> <html>
> <head>
>     <link rel="stylesheet" href="https://pyscript.net/alpha/pyscript.css"/>
>     <script defer src="https://pyscript.net/alpha/pyscript.js"></script>
> </head>
> 
> <body>
>     <py-script>
> print("hello, world!")
>     </py-script>
> </body>
> </html>
> ```

@jezdez now it's working I almost forgot that I'm writing python not html :). That's why forgot to put indentation .
