### ISSUE TITLE
[BUG] Error while importing xlsx file in pandas

### ISSUE THREAD

**Issue by Muzammiljethwa** [pyscript/pyscript#287]
**Describe the bug**

I was importing my data file to display a pandas table on web page so this error was occured
'ImportError: Missing optional dependency 'openpyxl'. Use pip or conda to install openpyxl'

**To Reproduce**
Steps to reproduce the behavior: either a code snippet or a link to an HTML page which shows the bug.

    <py-env>

    - pandas
    - paths:
        - /data.xlsx
    </py-env>

<body>

    <h1>TRY</h1>
    <py-script>

import pandas as pd

df = pd.read_excel("./data.xlsx")
df
            
    </py-script>|

</body>

**Expected behavior**

JsException(PythonError: Traceback (most recent call last): File "/lib/python3.10/site-packages/pandas/compat/_optional.py", line 138, in import_optional_dependency module = importlib.import_module(name) File "/lib/python3.10/importlib/__init__.py", line 126, in import_module return _bootstrap._gcd_import(name[level:], package, level) File "", line 1050, in _gcd_import File "", line 1027, in _find_and_load File "", line 1004, in _find_and_load_unlocked ModuleNotFoundError: No module named 'openpyxl' During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/lib/python3.10/site-packages/_pyodide/_base.py", line 429, in eval_code .run(globals, locals) File "/lib/python3.10/site-packages/_pyodide/_base.py", line 300, in run coroutine = eval(self.code, globals, locals) File "", line 4, in File "/lib/python3.10/site-packages/pandas/util/_decorators.py", line 311, in wrapper return func(*args, **kwargs) File "/lib/python3.10/site-packages/pandas/io/excel/_base.py", line 457, in read_excel io = ExcelFile(io, storage_options=storage_options, engine=engine) File "/lib/python3.10/site-packages/pandas/io/excel/_base.py", line 1419, in __init__ self._reader = self._engines[engine](self._io, storage_options=storage_options) File "/lib/python3.10/site-packages/pandas/io/excel/_openpyxl.py", line 524, in __init__ import_optional_dependency("openpyxl") File "/lib/python3.10/site-packages/pandas/compat/_optional.py", line 141, in import_optional_dependency raise ImportError(msg) ImportError: Missing optional dependency 'openpyxl'. Use pip or conda to install openpyxl. )

**Solution**
As the Error says you can easy resolve this by just installing the Package openpyxl: pip install openpyxl

**Comment by maximlt** [comment]
As you found out it's just a matter of adding `openpyxl` as a required dependency to PyScript's environment, as `openpyxl` is an optional dependency of `pandas`:

```html
<py-env>
- openpyxl
- pandas
- paths:
    - /data.xlsx
</py-env>
```

This issue can be closed since it's not related to PyScript usage but to pandas'.
