### ISSUE TITLE
[FEATURE] Requesting support for urllib or requests?

### ISSUE THREAD

**Issue by cohenaj194** [pyscript/pyscript#288]
**Is your feature request related to a problem? Please describe.**

I have a simple pyscript file that makes an HTTP request with urllib.  This is not supported and I find it gets the following error:

https://gist.githubusercontent.com/cohenaj194/58e79293e540244a883fe2e2d6c27e3c/raw/47a1e8c397d415be492c12c8aac16e390ab10cac/test.html

```
Let's plot random numbers
JsException(PythonError: Traceback (most recent call last): File "/lib/python3.10/urllib/request.py", line 1348, in do_open h.request(req.get_method(), req.selector, req.data, headers, File "/lib/python3.10/http/client.py", line 1282, in request self._send_request(method, url, body, headers, encode_chunked) File "/lib/python3.10/http/client.py", line 1328, in _send_request self.endheaders(body, encode_chunked=encode_chunked) File "/lib/python3.10/http/client.py", line 1277, in endheaders self._send_output(message_body, encode_chunked=encode_chunked) File "/lib/python3.10/http/client.py", line 1037, in _send_output self.send(msg) File "/lib/python3.10/http/client.py", line 975, in send self.connect() File "/lib/python3.10/http/client.py", line 941, in connect self.sock = self._create_connection( File "/lib/python3.10/socket.py", line 845, in create_connection raise err File "/lib/python3.10/socket.py", line 833, in create_connection sock.connect(sa) BlockingIOError: [Errno 26] Operation in progress During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/lib/python3.10/site-packages/_pyodide/_base.py", line 429, in eval_code .run(globals, locals) File "/lib/python3.10/site-packages/_pyodide/_base.py", line 300, in run coroutine = eval(self.code, globals, locals) File "", line 2, in File "/lib/python3.10/urllib/request.py", line 216, in urlopen return opener.open(url, data, timeout) File "/lib/python3.10/urllib/request.py", line 519, in open response = self._open(req, data) File "/lib/python3.10/urllib/request.py", line 536, in _open result = self._call_chain(self.handle_open, protocol, protocol + File "/lib/python3.10/urllib/request.py", line 496, in _call_chain result = func(*args) File "/lib/python3.10/urllib/request.py", line 1377, in http_open return self.do_open(http.client.HTTPConnection, req) File "/lib/python3.10/urllib/request.py", line 1351, in do_open raise URLError(err) urllib.error.URLError: )
```

**Describe the solution you'd like**
I would like a solution that allows me to make HTTP requests to external pages from a pyscript HTML file.

**Describe alternatives you've considered**
I have also attempted different python packages like `requests`, but at least having one from the Python standard library that works would be find. 

**Additional context**

Here is the code in case the gist does not work:

```
<html>
    <head>
      <link rel="stylesheet" href="https://pyscript.net/alpha/pyscript.css" />
      <script defer src="https://pyscript.net/alpha/pyscript.js"></script>
      <py-env>
        - numpy
        - matplotlib
      </py-env>
    </head>

  <body>
    <h1>Let's plot random numbers</h1>
    <div id="plot"></div>
    <py-script output="plot">
import urllib.request
with urllib.request.urlopen('http://python.org/') as response:
   html = response.read()
print (html)
    </py-script>
  </body>
</html>
```

**Comment by ckavidas** [comment]
See #91 

Pyscript devs should probably consider making an article explaining why urllib3/requests does not work since we see this issue posted very often.

You can use the pyodide methods below for making web requests in the meantime

https://pyodide.org/en/stable/usage/api/python-api.html

**Comment by philippjfr** [comment]
@ckavidas Indeed we are working on setting up documentation infrastructure and an FAQ which should cover this. I'll close as a duplicate. Thanks for filing the issue in any case @cohenaj194!
