### ISSUE TITLE
Import 3rd party modules, am I doing something wrong?

### ISSUE THREAD

**Issue by CleoMenezesJr** [pyscript/pyscript#314]
Following the [Toga example](https://github.com/pyscript/pyscript/tree/main/pyscriptjs/examples/toga) as a base, I am trying to import the Pykeepass module as follows:
```html
<py-env>
- './static/wheels/pykeepass-4.0.0-py3-none-any.whl'
</py-env>
```
However, it tells me that the wheels file was not found.

```console
Uncaught (in promise) PythonError: Traceback (most recent call last):
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 299, in add_wheel
    wheel_bytes = await fetch_bytes(wheel["url"])
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 55, in fetch_bytes
    return await (await pyfetch(url, **kwargs)).bytes()
  File "/lib/python3.10/site-packages/pyodide/http.py", line 149, in bytes
    self._raise_if_failed()
  File "/lib/python3.10/site-packages/pyodide/http.py", line 107, in _raise_if_failed
    raise OSError(
OSError: Request for ./static/wheels/pykeepass-4.0.0-py3-none-any.whl failed with status 404: File not found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 234, in __step
    result = coro.throw(exc)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 183, in install
    transaction = await self.gather_requirements(requirements, ctx, keep_going)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 173, in gather_requirements
    await gather(*requirement_promises)
  File "/lib/python3.10/asyncio/futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "/lib/python3.10/asyncio/tasks.py", line 304, in __wakeup
    future.result()
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 232, in __step
    result = coro.send(None)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 245, in add_requirement
    await self.add_wheel(name, wheel, version, (), ctx, transaction)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 304, in add_wheel
    raise ValueError(
ValueError: Couldn't fetch wheel from './static/wheels/pykeepass-4.0.0-py3-none-any.whl'.One common reason for this is when the server blocks Cross-Origin Resource Sharing (CORS).Check if the server is sending the correct 'Access-Control-Allow-Origin' header.
    PythonError error_handling.gen.ts:309
    new_error pyodide.asm.js:14
    method_call_trampoline pyodide.asm.js:14
    callPyObjectKwargs pyproxy.gen.ts:360
    callPyObject pyproxy.gen.ts:384
    wrapper pyodide.asm.js:14
error_handling.gen.ts:309:4

```
Sorry if somehow this is a stupid question or I just forgot something.

**Comment by JeffersGlass** [comment]
Unless you’re including special version of Pykeepass in your code for some reason, you can just have the following in your header

```
<py-env>
- pykeepass
</py-env>
```

Then import it into your Python code:

```
<py-script>
import pykeepass
…
</py-script>
```

Not every package on PyPi can be [Imported this way](https://pyodide.org/en/stable/usage/loading-packages.html), but [many can](https://pyodide.org/en/stable/usage/packages-in-pyodide.html) .

**Comment by CleoMenezesJr** [comment]
This fixed the error, but now it says it couldn't find a pure Python 3 wheel for 'pycryptodomex'.

```console
Uncaught (in promise) PythonError: Traceback (most recent call last):
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 234, in __step
    result = coro.throw(exc)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 183, in install
    transaction = await self.gather_requirements(requirements, ctx, keep_going)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 173, in gather_requirements
    await gather(*requirement_promises)
  File "/lib/python3.10/asyncio/futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "/lib/python3.10/asyncio/tasks.py", line 304, in __wakeup
    future.result()
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 232, in __step
    result = coro.send(None)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 286, in add_requirement
    raise ValueError(
ValueError: Couldn't find a pure Python 3 wheel for 'pycryptodomex'. You can use `micropip.install(..., keep_going=True)` to get a list of all packages with missing wheels.
```

I removed the static directory with the wheel file and now I have exactly this here in my html file:

```html
<!DOCTYPE html>
<html>
<head>
<link rel="stylesheet" href="https://pyscript.net/alpha/pyscript.css" />
<script defer src="https://pyscript.net/alpha/pyscript.js"></script>
<title>Page Title</title>
</head>
<body>

<p>
<label>Password: </label>
<input type="text" id="input1">
</p>
<py-env>
- pykeepass
</py-env>
<py-script>
from js import document
from pykeepass import PyKeePass

kp = PyKeePass('db.kdbx', password='password')
entry = kp.find_entries(title='Steam', first=True)
element = document.querySelector(f'#input1')
print(entry.password)
</py-script>

</body>
</html>
```

**Comment by JeffersGlass** [comment]
Ah, unfortunately it looks like PyKeepPass is imported some additional modules that micropip/pyodide can't handle. There's some discussion of building new packages/wheels for pyodide n Issue #85, but unfortunately it's not a simple nor universal process, sometimes requiring porting packages into WebAssembly (WASM) directly. That's unfortunately about as much as I personally know about the process.

**Comment by antocuni** [comment]
Unfortunately at the moment there is no solution for this. The non-pure python modules only work if they are supported by pyodide upstream, so if you want to include a new module you should probably open an issue there.
Sorry for that :)
