### ISSUE TITLE
[BUG] Importing sub-package in py-env section doesn't load sub-package packages

### ISSUE THREAD

**Issue by ptmcg** [pyscript/pyscript#383]
**Describe the bug**
When trying to load the subpackage `pyparsing[diagrams]`, I don't get the imported packages
See this gist, which has a workaround: https://gist.github.com/ptmcg/09b5be0cb3623a478851100488788821

This console snippet shows that pip installing `pyparsing[diagrams]` should install the railroad-diagrams and jinja2 packages

```
(py38_pyparsing) PS C:\Users\ptmcg> pip install pyparsing[diagrams]
Requirement already satisfied: pyparsing[diagrams] in c:\users\ptmcg\dev\venvs\py38_pyparsing\lib\site-packages (3.0.6)
Requirement already satisfied: railroad-diagrams in c:\users\ptmcg\dev\venvs\py38_pyparsing\lib\site-packages (from pyparsing[diagrams]) (1.1.0)
Requirement already satisfied: jinja2 in c:\users\ptmcg\dev\venvs\py38_pyparsing\lib\site-packages (from pyparsing[diagrams]) (2.11.2)
Requirement already satisfied: MarkupSafe>=0.23 in c:\users\ptmcg\dev\venvs\py38_pyparsing\lib\site-packages (from jinja2->pyparsing[diagrams]) (1.1.1)
WARNING: You are using pip version 20.3.3; however, version 22.1 is available.
You should consider upgrading via the 'c:\users\ptmcg\dev\venvs\py38_pyparsing\scripts\python.exe -m pip install --upgrade pip' command.
(py38_pyparsing) PS C:\Users\ptmcg> python
Python 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import jinja2
>>> import railroad
>>>
```

**To Reproduce**
This .html file fails:
```
<html>
    <head>
    <link rel="stylesheet" href="https://pyscript.net/alpha/pyscript.css" />
    <script defer src="https://pyscript.net/alpha/pyscript.js"></script>
    <py-env>
        - pyparsing[diagrams]
    </py-env>
    </head>

<body>
<py-script>
import jinja2

</py-script>
</html>
```

This is the traceback in the dev tools console:
```
Python exception:
Traceback (most recent call last):
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 429, in eval_code
    .run(globals, locals)
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 300, in run
    coroutine = eval(self.code, globals, locals)
  File "<exec>", line 1, in <module>
ModuleNotFoundError: No module named 'jinja2'
```

**Expected behavior**
Adding `pyparsing[diagrams]` should install the jinja2 and railroad-diagrams packages.

**Comment by yannickfunk** [comment]
PyScript internally installs packages via [micropip](https://pyodide.org/en/stable/usage/api/micropip-api.html

In your case, `micropip.install(pyparsing[diagrams])` is called.
`micropip.list()` then shows the following packages:

```
 Name      | Version | Source
--------- | ------- | -------
pyparsing | 3.0.7   | pyodide
micropip  | 0.1     | pyodide
packaging | 21.3    | pyodide
distutils | 1.0     | pyodide
```

So micropip does not install jinja, I would consider this a micropip issue, so please create an issue at [pyodide](https://github.com/pyodide/pyodide)

**Comment by rth** [comment]
For now micropip doesn't handle installation extras, but it's feature that should be add https://github.com/pyodide/pyodide/issues/2535

**Comment by marimeireles** [comment]
I'll close this one as a dup of your issue then @rth so we can keep the discussion centralized in one place :)
