### ISSUE TITLE
getting error when using pyodide.http 

### ISSUE THREAD

**Issue by dominicdev** [pyscript/pyscript#402]
when I'm trying to use pyodide.http call from a py-env

inside py
```
from pyodide.http import open_url
import json
def read_value(channel_name):
# print("channel_name" + channel_name)
output = open_url("[http://127.0.0.1:5000/get_channel/"+channel_name](http://127.0.0.1:5000/get_channel/%22+channel_name))

res_new = output.getvalue()
print("output " +res_new)
# res_new = {'data':[output.getvalue()]}
# result = json.dumps(res_new)
model_data = json.loads(res_new) 
print(model_data['data'][0]) 
print(model_data['data'][0]['channel_name'])  
channelName = model_data['data'][0]['channel_name']
Subscribers = int(float(model_data['data'][0]['Subscribers']))
Views = model_data['data'][0]['Views']
Videos = model_data['data'][0]['Videos']

 
return channelName,Subscribers,Views,Videos

```
Uncaught (in promise) PythonError: Traceback (most recent call last):
  File "/lib/python3.10/site-packages/packaging/requirements.py", line 102, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/lib/python3.10/site-packages/pyparsing/core.py", line 1134, in parse_string
    raise exc.with_traceback(None)
pyparsing.exceptions.ParseException: Expected W:(0-9A-Za-z), found '.'  (at char 0), (line:1, col:1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 234, in __step
    result = coro.throw(exc)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 183, in install
    transaction = await self.gather_requirements(requirements, ctx, keep_going)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 173, in gather_requirements
    await gather(*requirement_promises)
  File "/lib/python3.10/asyncio/futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "/lib/python3.10/asyncio/tasks.py", line 304, in __wakeup
    future.result()
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 232, in __step
    result = coro.send(None)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 248, in add_requirement
    req = Requirement(requirement)
  File "/lib/python3.10/site-packages/packaging/requirements.py", line 104, in __init__
    raise InvalidRequirement(
```
```

**Comment by marianoweber** [comment]
Can you share your HTML along with your python?
If you look at `antigravity.py` in the examples, it imports `from pyodide.http import open_url` as well and works just fine.

**Comment by dominicdev** [comment]
here is my full html code, not sure, but when I try to change it to other sample py it suddenly gets same error, it something to do with caching cause after I transfer my code in my py file in utils.py, it gets same error even after I undo get bring back the original code in utils.py it gets the same error, this happens when suddenly blackout in our area which sudden restart my pc hope could help me  

```
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1" />

    <title>PyScript youtube</title>

    <link rel="icon" type="image/png" href="favicon.png" />
    <link rel="stylesheet" href="https://pyscript.net/alpha/pyscript.css" />
    <script defer src="https://pyscript.net/alpha/pyscript.js"></script>

    <py-env> 
        - paths:
        - ./request_pyodide.py
    </py-env>
</head>
<style>
    input[type=text],
    select {
        width: 100%;
        padding: 12px 20px;
        margin: 8px 0;
        display: inline-block;
        border: 1px solid #ccc;
        border-radius: 4px;
        box-sizing: border-box;
    }

    input[type=submit] {
        width: 100%;
        background-color: #4c4faf;
        color: white;
        padding: 14px 20px;
        margin: 8px 0;
        border: none;
        border-radius: 4px;
        cursor: pointer;
    }

    input[type=submit]:hover {
        background-color: #45a049;
    }

    label {  
        font-size: 1.5rem;
        font-weight: bold; 
    }
    h2 {
        border-radius: 5px;
        background-color: #f2f2f2;
        padding: 20px;
        padding-top: 10px;
        padding-bottom: 10px;
        font-size: 2.5rem;
        font-weight: bold;
        text-align: center;
    }

    .p_container {
        border-radius: 5px;
        background-color: #f2f2f2;
        padding: 20px;
        padding-top: 10px;
        padding-bottom: 10px;
        display: flex;
        flex-direction: column;
        align-items: center;
        font-size: 1.5rem;
        font-weight: 500;
    }

    .p_container span {
        border-radius: 5px;
        background-color: #f2f2f2;
        padding: 0;
        font-size: 2rem;
        font-weight: 600;
    }

    table {
        border-spacing: 0;
        width: 100%;
        border: 1px solid #ddd;
    }

    th,
    td {
        text-align: left;
        padding: 16px;
    }

    tr:nth-child(even) {
        background-color: #f2f2f2
    }

    .main_container {
        width: 100%;
        max-width: 1200px;
        margin: auto;
    }

    .channel_container_info {
        padding: 20px;
        background-color: #f2f2f2;
    }

    .container_form {
        display: flex;
        justify-content: flex-start;
        flex-direction: column;
        margin-top: 50px;
    }

    .container_output {
        width: 100%;
        height: 100%;
        display: flex;
        flex-direction: column;
        align-items: center;
        margin: auto;

    }

    .tablecontainer {
        width: 100%;
        margin-top: 50px;
        margin-bottom: 150px;

    }
</style>

<body>
    <div class="main_container">
        <form class="container_form" onsubmit="return false">
            <label for="name">Select Channel:</label><br>
            <select name="channels" id="channels">
                <option value="Nicholas Renotte">Nicholas Renotte</option>
                <option value="Programming with Mosh">Programming with Mosh</option>
                <option value="AI Coffee Break with Letitia">AI Coffee Break with Letitia</option>
                <option value="Jeff Heaton">Jeff Heaton</option>
                <option value="Henry AI labs">Henry AI labs</option>
                <option value="Yannic kilcher">Yannic kilcher</option>
                <option value="Aladdin Persson">Aladdin Persson</option>
                <option value="Krish Naik">Krish Naik</option>
                <option value="Tech with Tim">Tech with Tim</option>
                <option value="NeuralNine">NeuralNine</option>
                <option value="What's AI">What's AI</option>
                <option value="The AI Epiphany">The AI Epiphany</option>
                <option value="Two minute papers">Two minute papers</option>
                <option value="Arxiv insights">Arxiv insights</option>
                <option value="Nerdy Rodent">Nerdy Rodent</option>
                <option value="Siraj Raval">Siraj Raval</option>
                <option value="AI Bites">AI Bites</option>
                <option value="Sebastian Lague">Sebastian Lague</option>
                <option value="1littlecoder">1littlecoder</option>
                <option value="Traversy Media">Traversy Media</option>
                <option value="Kalle Hallden">Kalle Hallden</option>
                <option value="Hvass Laboratories">Hvass Laboratories</option>
                <option value="deeplizard">deeplizard</option>
                <option value="ArjanCodes">ArjanCodes</option>
                <option value="Bakz T. Future">Bakz T. Future</option>
                <option value="HuggingFace">HuggingFace</option>
                <option value="James Briggs">James Briggs</option>
                <option value="Learn A.I. Now with LeakyAI">Learn A.I. Now with LeakyAI</option>
                <option value="Neuralearn">Neuralearn</option>
                <option value="Nicolai Nielsen - Computer Vision & AI">Nicolai Nielsen - Computer Vision & AI</option>
            </select>

            <input pys-onClick="sub" type="submit" id="btn-form" value="submit">

            <div class="channel_container_info">
                <h2 id='channelName'>Nicholas Renotte</h2>
                <p class="p_container">Total Subscriber<span id='subscribers'>74000</span></p>
                <p class="p_container">Total Videos<span id='totalvideos'>3,852,909</span></p>
                <p class="p_container">Total View<span id='totalviews'>3,852,909</span></p>
            </div>

 

            <py-script>  
                from request_pyodide import *
                import asyncio

                def sub(*args,**kwargs):
                    result_place_title = Element('channelName')
                    result_place_subscriber = Element('subscribers')
                    result_place_totalvideos = Element('totalvideos')
                    result_place_totalviews = Element('totalviews')
                    output = read_value(Element('channels').value)
                    result_place_title.write(f"{output[0]}")
                    result_place_subscriber.write(f"Subscribers: {output[1]}")
                    result_place_totalvideos.write(f"Total Videos: {output[2]}")
                    result_place_totalviews.write(f"total Views: {output[3]}")
            </py-script>
    </div>
</body>

</html>
```

**Comment by marianoweber** [comment]
Can you please indent `- ./request_pyodide.py` in py-env and test again?

**Comment by dominicdev** [comment]
> Can you please indent `- ./request_pyodide.py` in py-env and test again?

that seems fix issue. what was crazy, what I did was to format so fix the lines
