### ISSUE TITLE
[BUG] Python script in pyscript is unable to access internet

### ISSUE THREAD

**Issue by chekoduadarsh** [pyscript/pyscript#413]
**Describe the bug**
I was trying to get a CSV using pandas from web and I am getting following error

## My HTML script
``` html
<html><head>
    <meta charset="iso-8859-1">
    <link rel="icon" type="image/x-icon" href="./favicon.png">

    <link rel="stylesheet" href="https://pyscript.net/alpha/pyscript.css" />

    <script defer src="https://pyscript.net/alpha/pyscript.js"></script>

    </head>
    <body>
        <py-env>
- pandas
        </py-env>
        <div id="myplot"></div>

    <py-script id="main">
        import pandas as pd

        df = pd.read_csv("https://raw.githubusercontent.com/plotly/datasets/master/GanttChart.csv")
        data = [['tom', 10], ['nick', 15], ['juli', 14]]
  
        # Create the pandas DataFrame
        df = pd.DataFrame(data, columns = ['Name', 'Age'])
        df.head()
    </py-script>

</body>
</html>
``` 
## My error
``` python
Python exception:
Traceback (most recent call last):
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 429, in eval_code
    .run(globals, locals)
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 300, in run
    coroutine = eval(self.code, globals, locals)
  File "<exec>", line 3, in <module>
  File "/lib/python3.10/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 680, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 575, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 933, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1217, in _make_engine
    self.handles = get_handle(  # type: ignore[call-overload]
  File "/lib/python3.10/site-packages/pandas/io/common.py", line 670, in get_handle
    ioargs = _get_filepath_or_buffer(
  File "/lib/python3.10/site-packages/pandas/io/common.py", line 339, in _get_filepath_or_buffer
    with urlopen(req_info) as req:
  File "/lib/python3.10/site-packages/pandas/io/common.py", line 239, in urlopen
    return urllib.request.urlopen(*args, **kwargs)
  File "/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/lib/python3.10/urllib/request.py", line 541, in _open
    return self._call_chain(self.handle_open, 'unknown',
  File "/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/lib/python3.10/urllib/request.py", line 1419, in unknown_open
    raise URLError('unknown url type: %s' % type)
urllib.error.URLError: <urlopen error unknown url type: https>

```

**To Reproduce**
Run the HTML script given above

**Expected behavior**
Pyscript able to access internet without issues

**Screenshots**
![2022-05-18_19-34](https://user-images.githubusercontent.com/26855534/169060604-7db82d37-c07c-435f-9b20-b6eea0676a6b.png)

**Additional context**
None

**Comment by JeffersGlass** [comment]
The urllib.requests module does not work in PyScript for upstream reasons (the networking stack does not translate well to an in-browser environment). However, the team has definitely acknowledged that most users will come to PyScript expecting it to just work. (See #364 and #151 for work on that front, #91 for more explanation.).

For the time being, you may be able to use `pyodide.http.pyfetch` to get the date from the url, then use pandas to process it.

**Comment by philippjfr** [comment]
Thank you for the issue @chekoduadarsh and thank you @JeffersGlass for the excellent explanation. I'll close the issue as a duplicate.
