### ISSUE TITLE
[BUG] Error when running

### ISSUE THREAD

**Issue by UCYT5040** [pyscript/pyscript#459]
**Describe the bug**
Whenever I run the site, it doesn't show the regular runtime loading, and it displays this error.

**To Reproduce**
Just going to the page

**Expected behavior**
The code should be run

**Additional context**

```
PyScript encountered an error while loading from file: Traceback (most recent call last): File "/lib/python3.10/asyncio
/futures.py", line 201, in result raise self._exception File "/lib/python3.10/asyncio/tasks.py", line 232, in __step result = 
coro.send(None) File "/lib/python3.10/site-packages/_pyodide/_base.py", line 500, in eval_code_async await 
CodeRunner( File "/lib/python3.10/site-packages/_pyodide/_base.py", line 237, in __init__ self.ast = next(self._gen) File 
"/lib/python3.10/site-packages/_pyodide/_base.py", line 141, in _parse_and_compile_gen mod = compile(source, 
filename, mode, flags | ast.PyCF_ONLY_AST) File "", line 3 h1 { font-size: 1.5em; font-weight: normal; background-color: 
#9999cc; min-height:2em; line-height:2em; border-bottom: 1px inset black; margin: 0; } ^ SyntaxError: invalid decimal 
literal
```

**Comment by marianoweber** [comment]
Could you add a snippet to reproduce? Thanks!

**Comment by marimeireles** [comment]
Seems like a syntax error to me. Could you check @UCYT5040?
If it's not please post a reproducible as @marianoweber said.
Thanks.

**Comment by UCYT5040** [comment]
I won't be able to check for another 3 days, sorry for the wait.

**Comment by Advik-B** [comment]
@UCYT5040 . I found the answer.
you just downloaded the following to use pyscript locally
```
https://pyscript.net/alpha/pyscript.css
https://pyscript.net/alpha/pyscript.js
```
But... if you look at the console. we can see that pyscript is attempting to load pyscript.py from the local directory. (which does not exist) 
![image](https://user-images.githubusercontent.com/86160411/172913000-b5f466e2-2ca3-4df6-8986-e9ec9ab95039.png)

so.. I suggest you download all the ~~three~~four files and save them in the same directory

(Don't forget to download .js.map file.)
```
https://pyscript.net/alpha/pyscript.css
https://pyscript.net/alpha/pyscript.js
https://pyscript.net/alpha/pyscript.py
https://pyscript.net/alpha/pyscript.js.map

```
Then you can use them locally (whenever you use pyscript you MUST NOT FORGET THE `defer`):
So. I can use it like this:
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PyScript is cool</title>
</head>
<script defer src="pyscript/pyscript.js"></script>
<link rel="stylesheet" href="pyscript/pyscript.css">
<body>
    <h1>Welcome to placeholder website</h1>
<py-script>
print("Hello from PyScript")
</py-script>
</body>
</html>
```

## My setup...

![image](https://user-images.githubusercontent.com/86160411/172914931-6ef99d51-c67f-43f6-b80d-3ead328f61e3.png)

## The easy way is:
1. Download [pyscript.zip](https://github.com/pyscript/pyscript/files/8872845/pyscript.zip)
2. Unzip it in you project folder
3. import it using:
```html
<script defer src="pyscript/pyscript.js"></script>
<link rel="stylesheet" href="pyscript/pyscript.css"/>
```

## Side note

When you use py-script. DO NOT USE TABS (OR ANY FORMS OF INDENTATION)
example:

### Incorrect usage

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PyScript is cool</title>
</head>
<script defer src="pyscript/pyscript.js"></script>
<link rel="stylesheet" href="pyscript/pyscript.css">
<body>
    <h1>Welcome to placeholder website</h1>
    <py-script>
            print("Hello from PyScript")
    </py-script>
</body>
</html>
```
### Correct way
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PyScript is cool</title>
</head>
<script defer src="pyscript/pyscript.js"></script>
<link rel="stylesheet" href="pyscript/pyscript.css">
<body>
    <h1>Welcome to placeholder website</h1>
<py-script>
print("Hello from PyScript")
</py-script>
</body>
</html>
```

**Comment by RuofengX** [comment]
I download only two files pyscript.js and css,  and ran it in VSCode's plugin Live server, and it turns out the similar problem:
```
PyScript encountered an error while loading from file: Traceback (most recent call last): File "/lib/python3.10/asyncio/futures.py", line 201, in result raise self._exception File "/lib/python3.10/asyncio/tasks.py", line 232, in __step result = coro.send(None) File "/lib/python3.10/site-packages/_pyodide/_base.py", line 500, in eval_code_async await CodeRunner( File "/lib/python3.10/site-packages/_pyodide/_base.py", line 237, in __init__ self.ast = next(self._gen) File "/lib/python3.10/site-packages/_pyodide/_base.py", line 141, in _parse_and_compile_gen mod = compile(source, filename, mode, flags | ast.PyCF_ONLY_AST) File "", line 1 ^ SyntaxError: invalid syntax
```

but, if I use 
```
<link rel="stylesheet" href="https://pyscript.net/alpha/pyscript.css" />
<script defer src="https://pyscript.net/alpha/pyscript.js"></script>
```
to load script, it works.

So I downloaded those 4 files, then it works.
```
https://pyscript.net/alpha/pyscript.css
https://pyscript.net/alpha/pyscript.js
https://pyscript.net/alpha/pyscript.py
https://pyscript.net/alpha/pyscript.js.map
```

**Comment by Advik-B** [comment]
@RuofengX , You are most welcome ❤️
