### ISSUE TITLE
multiprocessing module not working as expected - _multiprocessing missing (not supported?!)

### ISSUE THREAD

**Issue by pawelgnatowski** [pyscript/pyscript#476]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

does anyone have a workaround? - I have seen this popping in other places (the bug) related to pyodine 
I am trying to port python rest api wrapper to Py Script here is where i get stuck:
 :
`from requests_futures.sessions import FuturesSession File "/lib/python3.10/site-packages/requests_futures/sessions.py", line 22, in from concurrent.futures import ThreadPoolExecutor, ProcessPoolExecutor File "/lib/python3.10/concurrent/futures/__init__.py", line 44, in __getattr__ from .process import ProcessPoolExecutor as pe File "/lib/python3.10/concurrent/futures/process.py", line 52, in import multiprocessing.connection File "/lib/python3.10/multiprocessing/connection.py", line 21, in import _multiprocessing ModuleNotFoundError: No module named '_multiprocessing' )`

### What browsers are you seeing the problem on? (if applicable)

Firefox, Chrome, Microsoft Edge

### Console info

```shell
Element.write: PythonError: Traceback (most recent call last):
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 429, in eval_code
    .run(globals, locals)
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 300, in run
    coroutine = eval(self.code, globals, locals)
  File "<exec>", line 1, in <module>
  File "/lib/python3.10/site-packages/mstrio/connection.py", line 14, in <module>
    from mstrio.api import authentication, exceptions, hooks, misc, projects
  File "/lib/python3.10/site-packages/mstrio/api/authentication.py", line 1, in <module>
    from mstrio.utils.error_handlers import ErrorHandler
  File "/lib/python3.10/site-packages/mstrio/utils/error_handlers.py", line 9, in <module>
    from mstrio.utils.helper import get_default_args_from_func, response_handler
  File "/lib/python3.10/site-packages/mstrio/utils/helper.py", line 22, in <module>
    from mstrio.utils.sessions import FuturesSessionWithRenewal
  File "/lib/python3.10/site-packages/mstrio/utils/sessions.py", line 2, in <module>
    from requests_futures.sessions import FuturesSession
  File "/lib/python3.10/site-packages/requests_futures/sessions.py", line 22, in <module>
    from concurrent.futures import ThreadPoolExecutor, ProcessPoolExecutor
  File "/lib/python3.10/concurrent/futures/__init__.py", line 44, in __getattr__
    from .process import ProcessPoolExecutor as pe
  File "/lib/python3.10/concurrent/futures/process.py", line 52, in <module>
    import multiprocessing.connection
  File "/lib/python3.10/multiprocessing/connection.py", line 21, in <module>
    import _multiprocessing
ModuleNotFoundError: No module named '_multiprocessing'
 --> True
pyodide.asm.js:14 APPENDING: True ==> py-e2ea188e-e67d-3b81-a6a1-29496b53272c --> PythonError: Traceback (most recent call last):
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 429, in eval_code
    .run(globals, locals)
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 300, in run
    coroutine = eval(self.code, globals, locals)
  File "<exec>", line 1, in <module>
  File "/lib/python3.10/site-packages/mstrio/connection.py", line 14, in <module>
    from mstrio.api import authentication, exceptions, hooks, misc, projects
  File "/lib/python3.10/site-packages/mstrio/api/authentication.py", line 1, in <module>
    from mstrio.utils.error_handlers import ErrorHandler
  File "/lib/python3.10/site-packages/mstrio/utils/error_handlers.py", line 9, in <module>
    from mstrio.utils.helper import get_default_args_from_func, response_handler
  File "/lib/python3.10/site-packages/mstrio/utils/helper.py", line 22, in <module>
    from mstrio.utils.sessions import FuturesSessionWithRenewal
  File "/lib/python3.10/site-packages/mstrio/utils/sessions.py", line 2, in <module>
    from requests_futures.sessions import FuturesSession
  File "/lib/python3.10/site-packages/requests_futures/sessions.py", line 22, in <module>
    from concurrent.futures import ThreadPoolExecutor, ProcessPoolExecutor
  File "/lib/python3.10/concurrent/futures/__init__.py", line 44, in __getattr__
    from .process import ProcessPoolExecutor as pe
  File "/lib/python3.10/concurrent/futures/process.py", line 52, in <module>
    import multiprocessing.connection
  File "/lib/python3.10/multiprocessing/connection.py", line 21, in <module>
    import _multiprocessing
ModuleNotFoundError: No module named '_multiprocessing'

base.ts:128 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'setAttribute')
    at PyScript.evaluate (base.ts:128:79)
evaluate @ base.ts:128
await in evaluate (async)
initialize @ pyconfig.ts:75
await in initialize (async)
(anonymous) @ pyconfig.ts:130
load (async)
loadRuntimes @ pyconfig.ts:129
connectedCallback @ pyconfig.ts:113
(anonymous) @ main.ts:27
(anonymous) @ main.ts:35
pyscript.ts:111 Collecting nodes...
```

### Additional Context

somewhat related issue?
https://github.com/oracle/graalpython/issues/58
https://github.com/pyodide/pyodide/issues/1603

Does that mean it will not arrive?

**Comment by yannickfunk** [comment]
Thank you for submitting the issue! As stated in the issue linked by you (https://github.com/pyodide/pyodide/issues/1603) 

> multiprocessing won't work in Pyodide because one cannot create processes (and threads for now).

Since pyodide is the python runtime pyscript uses, it can also not support multiprocessing.

**Comment by pawelgnatowski** [comment]
Thank you for your prompt reply. Best of luck with the project!

**Comment by marimeireles** [comment]
Hey @pawelgnatowski, I think you pretty much tracked down the issue.
This is the umbrella issue where pyodide folks are discussing the state of threading: https://github.com/pyodide/pyodide/issues/237. Did you see that there's a work around in the issue you posted? That might work for you.
BTW, just because we won't address it now it doesn't mean we won't address it there are lots of interest around that and we hope to tackle it in the future!

**Comment by pawelgnatowski** [comment]
@marimeireles Will certainly look into this in more depth. Thank you for clariication.

For context - the library i am trying to port has a monthly cadence release - which of I am not the owner of. As I might be able to make it work, then the maintenance will be difficult.
Moreover, as a general concept i want to try out Pyscript for data analytics /visualization, rather than simple JS/CSS/HTML replacement. Python is now more Data Science than R. I see PyScript's potential here somehow.
