### ISSUE TITLE
Panel streaming demo example is buggy but works

### ISSUE THREAD

**Issue by marimeireles** [pyscript/pyscript#484]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

On firefox only:

```
Uncaught (in promise) TypeError: this.errorElement.children[(this.errorElement.children.length - 1)] is undefined
    evaluate base.ts:128
    initialize pyconfig.ts:75
    loadRuntimes pyconfig.ts:130
    loadRuntimes pyconfig.ts:129
    connectedCallback pyconfig.ts:113
    app main.ts:27
    <anonymous> pyscript.js:27359
[base.ts:128:12](https://pyscript.net/src/components/base.ts)
    evaluate base.ts:130
    InterpretGeneratorResume self-hosted:1425
    AsyncFunctionNext self-hosted:635
    (Async: async)
    initialize pyconfig.ts:75
    InterpretGeneratorResume self-hosted:1425
    AsyncFunctionNext self-hosted:635
```
    
Besides several messages about pyodide issues:

```
pyodide.asm.js:14 Python exception:
Traceback (most recent call last):
  File "<exec>", line 164, in write
  File "<exec>", line 124, in write
  File "<exec>", line 82, in format_mime
TypeError: argument of type 'NoneType' is not iterable
```

On Chrome only:

```
base.ts:128 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'setAttribute')
    at PyScript.evaluate (base.ts:128:79)
```

This is not priority. I'm documenting it to keep track of it :)

**Comment by marimeireles** [comment]
Not relevant anymore.
Works again.

**Comment by Aprameya-S** [comment]
I'm getting the same errors. How did you resolve it?

**Comment by fpliger** [comment]
@Aprameya-S what version are you using?
