### ISSUE TITLE
Bug: setting runtime configuration to local pyodide.js occurs an exception

### ISSUE THREAD

**Issue by TutorExilius** [pyscript/pyscript#515]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

Hello! :)

I just wanted to let you know the following problem I occured:

I tried to build a progressive web app, by doing this I encountered the following error: 

When I use Flask and work with the following configuration

`    <py-config>
        autoclose_loader: true
        runtimes:
            - src: "./static/pyodide-0.2.0/pyodide.js"
              name: pyodide-0.20
              lang: python
    </py-config>`
    
the following exception occured (see screenshot):
![grafik](https://user-images.githubusercontent.com/26031405/173433595-732a948b-6ad8-422f-bda4-74e4fa8e49b8.png)

The problem is that fetching the local pyodide.asm.js file (here: http://localhost:5000/static/pyodide-0.2.0/pyodide.asm.js) is served with the mimetype "text/plain".

To solve that problem I had to route the resource and adjusting the mimetype as follows:

`@app.route("/static/pyodide-0.2.0/pyodide.asm.js")
def pyodide_asm_js():
    js = Path(__file__).parent / 'static' / 'pyodide-0.2.0' / 'pyodide.asm.js'
    text = js.read_text()
    resp = make_response(text)
    resp.content_type = 'application/javascript'

    return resp`

### What browsers are you seeing the problem on? (if applicable)

Firefox, Chrome

### Console info

```shell
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.
pwa-scaffold.js:5 service worker registered ServiceWorkerRegistration
pyconfig.ts:133 Uncaught (in promise) TypeError: Failed to fetch dynamically imported module: http://localhost:5000/static/pyodide-0.2.0/pyodide.asm.js
```

**Comment by leriomaggio** [comment]
I second this, but I have the impression that what happens in my case is a bit different. 

I am using the `latest` version from PyScript CDN along with a compiled-from-source version of `Pyodide` (i.e. `0.22.0-dev0`)

```html
   <link rel="stylesheet" href="https://pyscript.net/latest/pyscript.css"/>
    <script defer src="https://pyscript.net/latest/pyscript.js"></script>
    <py-config>
        - autoclose_loader: true
        - runtimes:
          - src: "./pyodide/pyodide.js"
            name: pyodide-0.22.0.dev0
            lang: python
    </py-config>
```

It seems that the `py-config` directive is completely ignored: there is no trace in my browser inspector of the local `pyodide.js` being fetched, whilst the default built-in pyodide is loaded from cdn (`pyodide-0.20.0`). 
As a result, the interpreter fails to parse my code with 

```python
Element.write: PythonError: Traceback (most recent call last):
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 232, in __step
    result = coro.send(None)
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 500, in eval_code_async
    await CodeRunner(
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 351, in run_async
    coroutine = eval(self.code, globals, locals)
  File "<exec>", line 7, in <module>
ModuleNotFoundError: No module named 'pyodide.ffi'
 --> True
```

The new Pyodide API has moved `create_proxy` to the `ffi` package which is not found, clearly demonstrating the old API is being used by PyScript.

Goes without saying, the same code works perfectly with PyScript `alpha` version.

**Comment by leriomaggio** [comment]
Re runtime configuration with `latest` PyScript: as a matter of facts, it seems it's not specifically a matter of local Pyodide, but more generally with the `py-config` tag getting ignore. 

Changed with a different Pyodide version from CDN - as shown below - and still doesn't work

```html
    <py-config>
        - autoclose_loader: true
        - runtimes:
          - src: "https://cdn.jsdelivr.net/pyodide/v0.21.3/full/pyodide.js"
            name: pyodide-0.21.3
            lang: python
    </py-config>
```

Again, this works perfectly with `alpha` release

HTH
