### ISSUE TITLE
Using pygame in pyscript 

### ISSUE THREAD

**Issue by Python-Ninja-Hebi** [pyscript/pyscript#592]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a duplication
- [X] I already searched in Google and didn't find any good information or help

### What is the issue/comment/problem?

I would like to use pygame in pyscript.

Do you use pyodide 3.11 so pygame should work?

https://github.com/pygame/pygame/issues/718#issuecomment-1179793633

Best Regards Hebi

**Comment by marimeireles** [comment]
Are you encountering an error?
Please add it here.

**Comment by manuel-delverme** [comment]
hijacking since I'm facing the same issue, this is my error
```
Uncaught (in promise) PythonError: Traceback (most recent call last):
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 234, in __step
    result = coro.throw(exc)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 183, in install
    transaction = await self.gather_requirements(requirements, ctx, keep_going)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 173, in gather_requirements
    await gather(*requirement_promises)
  File "/lib/python3.10/asyncio/futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "/lib/python3.10/asyncio/tasks.py", line 304, in __wakeup
    future.result()
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 232, in __step
    result = coro.send(None)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 286, in add_requirement
    raise ValueError(
ValueError: Couldn't find a pure Python 3 wheel for 'pygame'. You can use `micropip.install(..., keep_going=True)` to get a list of all packages with missing wheels.

    at new_error (pyodide.asm.js:14:238191)
    at pyodide.asm.wasm:0xedbcb
    at pyodide.asm.wasm:0xf1a0e
    at method_call_trampoline (pyodide.asm.js:14:238105)
    at pyodide.asm.wasm:0x134c2c
    at pyodide.asm.wasm:0x217a84
    at pyodide.asm.wasm:0x174a14
    at pyodide.asm.wasm:0x135149
    at pyodide.asm.wasm:0x135243
    at pyodide.asm.wasm:0x1352e6
    at pyodide.asm.wasm:0x1fff83
    at pyodide.asm.wasm:0x1f98b5
    at pyodide.asm.wasm:0x135329
    at pyodide.asm.wasm:0x201f1b
    at pyodide.asm.wasm:0x1ff9ff
    at pyodide.asm.wasm:0x1f98b5
    at pyodide.asm.wasm:0x135329
    at pyodide.asm.wasm:0xf16d8
    at Module.callPyObjectKwargs (pyproxy.gen.ts:360:23)
    at Module.callPyObject (pyproxy.gen.ts:384:17)
    at wrapper (pyodide.asm.js:14:205222)
```

**Comment by pmp-p** [comment]
hi, it's a pyodide issue to follow here https://github.com/pyodide/pyodide/issues/289
i won't backport pygame to 3.10 because there are numpy issues, it is way simpler for [pygame-web](https://pygame-web.github.io/) to be patient and load all pyodide 3.11 modules with pip and be used directly as pyscript engine than the other way around.

pygame use and will follow only CPython upstream build system, but i'll make sure to gain compatibility with pyscript.

**Comment by marimeireles** [comment]
Oh cool, so that means that the 3.11 is working?
This is good news for @ntoll 
Thanks for letting us know @pmp-p, we're big fans of `pygame` here at PyScript 😄
I'm closing this as no-fix for now... Maybe in the future?
