### ISSUE TITLE
can't get beautifulsoup to run

### ISSUE THREAD

**Issue by Anas-jaf** [pyscript/pyscript#687]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

when i run pyscript from the cdn and import beautifulsoup i get the error that there is no module named bs4

![image](https://user-images.githubusercontent.com/63655663/184463258-ff408964-05ee-44d6-8223-05c9d42ed2e3.png)

### Console info

```shell
JsException(PythonError: Traceback (most recent call last): File "/lib/python3.10/site-packages/_pyodide/_base.py", line 429, in eval_code .run(globals, locals) File "/lib/python3.10/site-packages/_pyodide/_base.py", line 300, in run coroutine = eval(self.code, globals, locals) File "", line 1, in ModuleNotFoundError: No module named 'bs4' )
```

**Comment by Anas-jaf** [comment]
i found solution from YouTube video maybe i didn't read the documentation good 
i solved this with< py-env> tag

**Comment by Anas-jaf** [comment]
found soloution
