### ISSUE TITLE
Specifying dependencies in `<py-env>` is not equivalent to `micropip.install()`

### ISSUE THREAD

**Issue by astrojuanlu** [pyscript/pyscript#736]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

My end goal is to install `rst-to-myst` on PyScript, but I'm running into some walls related to dependency versions.

While debugging on the Pyodide console, I managed to install it by pinning the exact versions of some key dependencies:

```
>>> import micropip
>>> await micropip.install(["mdformat-myst==0.1.4", "ruamel-yaml==0.16.13", "mdformat-deflist==0.1.1", "rst-to-myst==0.3.2"])
>>> micropip.list()
Name                 | Version | Source
-------------------- | ------- | -------
micropip             | 0.1     | pyodide
packaging            | 21.3    | pyodide
pyparsing            | 3.0.9   | pyodide
ruamel.yaml          | 0.16.13 | pypi
mdformat_tables      | 0.4.1   | pypi
mdformat_frontmatter | 0.4.1   | pypi
mdformat             | 0.7.16  | pypi
markdown-it-py       | 1.1.0   | pypi
mdit-py-plugins      | 0.2.8   | pypi
six                  | 1.16.0  | pyodide
attrs                | 21.4.0  | pyodide
mdformat_myst        | 0.1.4   | pypi
tomli                | 2.0.1   | pyodide
mdformat_deflist     | 0.1.1   | pypi
click                | 7.1.2   | pypi
docutils             | 0.17.1  | pypi
rst-to-myst          | 0.3.2   | pypi
PyYAML               | 6.0     | pyodide
distutils            | 1.0     | pyodide
>>> import rst_to_myst
>>> rst_to_myst.__version__
'0.3.2'
>>> print(rst_to_myst.rst_to_myst("""
... Title
... =====
... 
... Hello, `stranger <https://google.com/>`_!
... """,
... use_sphinx=False,
... ).text)
# Title
Hello, [stranger](https://google.com/)!
```

However, while trying to reproduce that on PyScript, I can't get the dependencies installed:

```
environment loading... Array(4) [ "mdformat-myst==0.1.4", "ruamel-yaml==0.16.13", "mdformat-deflist==0.1.1", "rst-to-myst==0.3.2" ]
Collecting nodes to be mounted into python namespace...
Uncaught (in promise) PythonError: Traceback (most recent call last):
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 234, in __step
    result = coro.throw(exc)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 183, in install
    transaction = await self.gather_requirements(requirements, ctx, keep_going)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 173, in gather_requirements
    await gather(*requirement_promises)
  File "/lib/python3.10/asyncio/futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "/lib/python3.10/asyncio/tasks.py", line 304, in __wakeup
    future.result()
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 232, in __step
    result = coro.send(None)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 291, in add_requirement
    await self.add_wheel(
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 316, in add_wheel
    await self.add_requirement(recurs_req, ctx, transaction)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 291, in add_requirement
    await self.add_wheel(
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 316, in add_wheel
    await self.add_requirement(recurs_req, ctx, transaction)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 286, in add_requirement
    raise ValueError(
ValueError: Couldn't find a pure Python 3 wheel for 'ruamel.yaml.clib>=0.2.6; platform_python_implementation == "CPython" and python_version < "3.11"'. You can use `micropip.install(..., keep_going=True)` to get a list of all packages with missing wheels.
```

(Essentially I'm hitting https://github.com/pyodide/pyodide/issues/3034, but it's difficult to see what package requested a newer version of the dependency, or where exactly the dependency resolution went south. See also https://github.com/pyodide/pyodide/issues/3035, where I describe why this particular package might be challenging to install with a naïve dependency resolving algorithm)

I tried to work around the issue by leaving the dependencies list empty and using `micropip` inside the script, but

- `await micropip.install()` doesn't work (error `await outside function`)
- `asyncio.run(micropip.install())` also doesn't work (`RuntimeError: asyncio.run() cannot be called from a running event loop`)
- `asyncio.get_running_loop().run_until_complete(micropip.install())` worked, but apparently by that time it's already too late and I keep getting `ModuleNotFoundError: No module named 'rst_to_myst'`

So, I'm kind of stuck here. Any advice?

### What browsers are you seeing the problem on? (if applicable)

Firefox, Chrome

### Console info

```shell
(Various errors, see above)
```

**Comment by fpliger** [comment]
@astrojuanlu I just tried to replicate with this HTML example and it seemed to be working fine. Am I missing something?

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1" />

    <title>Simple Clock Demo</title>

    <link rel="icon" type="image/png" href="favicon.png" />
    <link rel="stylesheet" href="../build/pyscript.css" />

    <script defer src="../build/pyscript.js"></script>
    <py-env>
    - mdformat-myst==0.1.4
    - ruamel-yaml==0.16.13
    - mdformat-deflist==0.1.1
    - rst-to-myst==0.3.2
    </py-env>
  </head>

  <body>
    <div class="font-mono">start time: <label id="outputDiv"></label></div>
    
    <py-script output="outputDiv">
import micropip
micropip.list()
    </py-script>
  </body>
</html>
```

**Comment by astrojuanlu** [comment]
Hi @fpliger, thanks for the quick response. I don't have a local build of `pyscript`, so I tried this diff with respect to your snippet:

```diff
$ diff -u index_ok.html index2.html 
--- index_ok.html       2022-08-29 20:36:12.219300928 +0200
+++ index2.html 2022-08-29 20:35:50.767440680 +0200
@@ -7,9 +7,8 @@
     <title>Simple Clock Demo</title>
 
     <link rel="icon" type="image/png" href="favicon.png" />
-    <link rel="stylesheet" href="../build/pyscript.css" />
-
-    <script defer src="../build/pyscript.js"></script>
+    <link rel="stylesheet" href="https://pyscript.net/alpha/pyscript.css" />
+    <script defer src="https://pyscript.net/alpha/pyscript.js"></script>
     <py-env>
     - mdformat-myst==0.1.4
     - ruamel-yaml==0.16.13
```

and I observe the error. Does this mean that it has probably been fixed in the `main` branch?

**Comment by astrojuanlu** [comment]
I tried using the "Download" option rather than the "Install" option from [the website](https://pyscript.net/), but looks like these instructions are incomplete:

![image](https://user-images.githubusercontent.com/316517/187274553-e63bb757-cc02-464c-a915-d90f673e1d7b.png)

It should say (1) download, (2) unzip, (3) **follow the build instructions**, and (4) copy the assets you want? (Happy to make this a separate issue)

**Comment by fpliger** [comment]
Ah! Ok.. So, there are a couple of things going on here... 

1. Is that you are using PyScript `alpha` version. You should update to `latest`. So your links should be `https://pyscript.net/latest/pyscript`. Unfortunately, we didn't do a good job socializing that on the main side page and have an issue to update links there.  Should be fixing that soon
2. I think there's also an upstream issue going on that should be resolved with the latest version of Pyodide. 

Here's an example that should work:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1" />

    <title>Simple Clock Demo</title>

    <link rel="icon" type="image/png" href="favicon.png" />
    <link rel="stylesheet" href="https://pyscript.net/latest/pyscript.css" />

    <script defer src="https://pyscript.net/a/pyscript.js"></script>
    <py-config>
    autoclose_loader: true
    runtimes:
      - src: "https://cdn.jsdelivr.net/pyodide/v0.21.1/full/pyodide.js"
        name: pyodide-0.21
        lang: python
    </py-config>
    <py-env>
    - mdformat-myst==0.1.4
    - ruamel-yaml==0.16.13
    - mdformat-deflist==0.1.1
    - rst-to-myst==0.3.2
    </py-env>
  </head>

  <body>
    <div class="font-mono">start time: <label id="outputDiv"></label></div>
    
    <py-script output="outputDiv">
import micropip
micropip.list()
    </py-script>
  </body>
</html>
```

Can you confirm?

**Comment by astrojuanlu** [comment]
Using `latest` pyscript + pyodide 0.21.1 worked! 🎉 I'll continue doing the work, leaving it up to you if you want to close the issue.

**Comment by fpliger** [comment]
Awesome🎉🎉! I'll close the issue since I think we already have another one to capture the links to `latest` vs `alpha`.

Thank you for opening it and for your patience! :)
