### ISSUE TITLE
Error in py-env sqlite3

### ISSUE THREAD

**Issue by auguzsto** [pyscript/pyscript#787]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

When importing the sqlite3 package on the <py-env> page, it cannot perform the import.

Image of code:
-

![image](https://user-images.githubusercontent.com/40308971/192104487-a1015b21-043a-4718-a611-25e6a114c22e.png)
-
Image of console. Part1:
-

![image](https://user-images.githubusercontent.com/40308971/192104531-f0d3596a-c6a7-41fd-a943-29c16dc5de69.png)
-
Image of console. Part2:
-

![image](https://user-images.githubusercontent.com/40308971/192104571-e592289e-2473-4898-93ee-07b8bccd353f.png)

Thx!

### What browsers are you seeing the problem on? (if applicable)

Chrome

### Console info

```shell
adding initializer async ƒ mountElements() {
        console.log('Collecting nodes to be mounted into python namespace...');
        const pyodide = await pyodideReadyPromise$1;
        const matches = document.querySelectorAl…
stores.ts:34 added initializer async ƒ mountElements() {
        console.log('Collecting nodes to be mounted into python namespace...');
        const pyodide = await pyodideReadyPromise$1;
        const matches = document.querySelectorAl…
stores.ts:40 adding post initializer async ƒ initHandlers() {
        console.log('Collecting nodes...');
        const pyodide = await pyodideReadyPromise$1;
        for (const pysAttribute of pysAttributeToEvent.keys()) {
            await cr…
stores.ts:42 added post initializer async ƒ initHandlers() {
        console.log('Collecting nodes...');
        const pyodide = await pyodideReadyPromise$1;
        for (const pysAttribute of pysAttributeToEvent.keys()) {
            await cr…
pyenv.ts:10 RUNTIME READY
pyconfig.ts:17 config set!
pyconfig.ts:22 initializers set
pyconfig.ts:27 post initializers set
pyconfig.ts:32 post initializers set
pyconfig.ts:37 post initializers set
pyconfig.ts:32 post initializers set
pyscript.ts:66 connected
stores.ts:32 adding initializer async ƒ loadEnv() {
                await loadPackage(env);
                console.log('environment loaded');
            }
pyconfig.ts:22 initializers set
stores.ts:34 added initializer async ƒ loadEnv() {
                await loadPackage(env);
                console.log('environment loaded');
            }
stores.ts:32 adding initializer async ƒ loadPaths() {
                for (const singleFile of paths) {
                    console.log(`loading ${singleFile}`);
                    try {
                        await loadFromFile(singleFi…
pyconfig.ts:22 initializers set
stores.ts:34 added initializer async ƒ loadPaths() {
                for (const singleFile of paths) {
                    console.log(`loading ${singleFile}`);
                    try {
                        await loadFromFile(singleFi…
pyenv.ts:60 environment loading... ['sqlite3']
pyconfig.ts:17 config set!
pyconfig.ts:115 config set {autoclose_loader: true, runtimes: Array(1)}
pyconfig.ts:127 Initializing runtimes...
interpreter.ts:8 creating pyodide runtime
pyodide.asm.js:14 Python initialization complete
interpreter.ts:18 loading micropip
load-package.ts:329 Loading micropip, pyparsing, packaging, distutils
load-package.ts:389 Loaded micropip, pyparsing, packaging, distutils
interpreter.ts:20 loading pyscript...
pyodide.asm.js:14 [Violation] 'setTimeout' handler took 1205ms
interpreter.ts:22 done setting up environment
pyenv.ts:10 RUNTIME READY
pyscript.ts:148 Collecting nodes to be mounted into python namespace...
index.html:1 Access to fetch at 'https://pypi.org/pypi/sqlite3/json' from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
pyodide.asm.js:14          GET https://pypi.org/pypi/sqlite3/json net::ERR_FAILED 404
hiwire_call_bound @ pyodide.asm.js:14
$func380 @ pyodide.asm.wasm:0xef536
$func3167 @ pyodide.asm.wasm:0x201f1b
$_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x1ff173
$func1364 @ pyodide.asm.wasm:0x1487f2
$func1385 @ pyodide.asm.wasm:0x14968c
$PyIter_Send @ pyodide.asm.wasm:0x121bcf
$_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x1fc373
$func1364 @ pyodide.asm.wasm:0x1487f2
$func1385 @ pyodide.asm.wasm:0x14968c
$PyIter_Send @ pyodide.asm.wasm:0x121bcf
$_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x1fc373
$func1364 @ pyodide.asm.wasm:0x1487f2
$func1385 @ pyodide.asm.wasm:0x14968c
$PyIter_Send @ pyodide.asm.wasm:0x121bcf
$_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x1fc373
$func1364 @ pyodide.asm.wasm:0x1487f2
$func1356 @ pyodide.asm.wasm:0x147ef7
$func1386 @ pyodide.asm.wasm:0x14969a
method_call_trampoline @ pyodide.asm.js:14
$func1176 @ pyodide.asm.wasm:0x13d52c
$func3167 @ pyodide.asm.wasm:0x201f1b
$_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x1ff9ff
$_PyEval_Vector @ pyodide.asm.wasm:0x1f98b5
$_PyFunction_Vectorcall @ pyodide.asm.wasm:0x135329
$func1080 @ pyodide.asm.wasm:0x136cde
$func3330 @ pyodide.asm.wasm:0x217a98
$func1954 @ pyodide.asm.wasm:0x174a14
$PyVectorcall_Call @ pyodide.asm.wasm:0x135149
$_PyObject_Call @ pyodide.asm.wasm:0x135243
$PyObject_Call @ pyodide.asm.wasm:0x1352e6
$_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x1fff83
$_PyEval_Vector @ pyodide.asm.wasm:0x1f98b5
$_PyFunction_Vectorcall @ pyodide.asm.wasm:0x135329
$func3167 @ pyodide.asm.wasm:0x201f1b
$_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x1ff9ff
$_PyEval_Vector @ pyodide.asm.wasm:0x1f98b5
$_PyFunction_Vectorcall @ pyodide.asm.wasm:0x135329
$_pyproxy_apply @ pyodide.asm.wasm:0xf16d8
Module.callPyObjectKwargs @ pyproxy.gen.ts:360
Module.callPyObject @ pyproxy.gen.ts:384
wrapper @ pyodide.asm.js:14
setTimeout (assíncrono)
hiwire_call_bound @ pyodide.asm.js:14
$func380 @ pyodide.asm.wasm:0xef536
$func3167 @ pyodide.asm.wasm:0x201f1b
$_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x1ff173
$_PyEval_Vector @ pyodide.asm.wasm:0x1f98b5
$_PyFunction_Vectorcall @ pyodide.asm.wasm:0x135329
$func1080 @ pyodide.asm.wasm:0x136c6e
$PyVectorcall_Call @ pyodide.asm.wasm:0x135186
$_PyObject_Call @ pyodide.asm.wasm:0x135243
$PyObject_Call @ pyodide.asm.wasm:0x1352e6
$_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x1fff83
$_PyEval_Vector @ pyodide.asm.wasm:0x1f98b5
$_PyFunction_Vectorcall @ pyodide.asm.wasm:0x135329
$func1080 @ pyodide.asm.wasm:0x136c6e
$func3167 @ pyodide.asm.wasm:0x201f1b
$_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x1ffa4e
$_PyEval_Vector @ pyodide.asm.wasm:0x1f98b5
$_PyFunction_Vectorcall @ pyodide.asm.wasm:0x135329
$_PyObject_FastCallDictTstate @ pyodide.asm.wasm:0x134d4d
$_PyObject_Call_Prepend @ pyodide.asm.wasm:0x13552f
$func2435 @ pyodide.asm.wasm:0x1932a4
$func2336 @ pyodide.asm.wasm:0x18ad4c
method_call_trampoline @ pyodide.asm.js:14
$_PyObject_MakeTpCall @ pyodide.asm.wasm:0x134c2c
$func3167 @ pyodide.asm.wasm:0x201efe
$_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x1ffa4e
$_PyEval_Vector @ pyodide.asm.wasm:0x1f98b5
$_PyFunction_Vectorcall @ pyodide.asm.wasm:0x135329
$func3167 @ pyodide.asm.wasm:0x201f1b
$_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x1ff9ff
$_PyEval_Vector @ pyodide.asm.wasm:0x1f98b5
$_PyFunction_Vectorcall @ pyodide.asm.wasm:0x135329
$func3167 @ pyodide.asm.wasm:0x201f1b
$_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x1ffa4e
$_PyEval_Vector @ pyodide.asm.wasm:0x1f98b5
$_PyFunction_Vectorcall @ pyodide.asm.wasm:0x135329
$PyVectorcall_Call @ pyodide.asm.wasm:0x135149
$_PyObject_Call @ pyodide.asm.wasm:0x135243
$PyObject_Call @ pyodide.asm.wasm:0x1352e6
$_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x1fff83
$func1364 @ pyodide.asm.wasm:0x1487f2
$func1385 @ pyodide.asm.wasm:0x14968c
$PyIter_Send @ pyodide.asm.wasm:0x121bcf
$_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x1fc373
$func1364 @ pyodide.asm.wasm:0x1487f2
$func1356 @ pyodide.asm.wasm:0x147ef7
$func1386 @ pyodide.asm.wasm:0x14969a
method_call_trampoline @ pyodide.asm.js:14
$func1176 @ pyodide.asm.wasm:0x13d52c
$func3167 @ pyodide.asm.wasm:0x201f1b
$_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x1ff9ff
$_PyEval_Vector @ pyodide.asm.wasm:0x1f98b5
$_PyFunction_Vectorcall @ pyodide.asm.wasm:0x135329
$func1080 @ pyodide.asm.wasm:0x136cde
$func3330 @ pyodide.asm.wasm:0x217a98
$func1954 @ pyodide.asm.wasm:0x174a14
$PyVectorcall_Call @ pyodide.asm.wasm:0x135149
$_PyObject_Call @ pyodide.asm.wasm:0x135243
$PyObject_Call @ pyodide.asm.wasm:0x1352e6
$_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x1fff83
$_PyEval_Vector @ pyodide.asm.wasm:0x1f98b5
$_PyFunction_Vectorcall @ pyodide.asm.wasm:0x135329
$func3167 @ pyodide.asm.wasm:0x201f1b
$_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x1ff9ff
$_PyEval_Vector @ pyodide.asm.wasm:0x1f98b5
$_PyFunction_Vectorcall @ pyodide.asm.wasm:0x135329
$_pyproxy_apply @ pyodide.asm.wasm:0xf16d8
Module.callPyObjectKwargs @ pyproxy.gen.ts:360
Module.callPyObject @ pyproxy.gen.ts:384
wrapper @ pyodide.asm.js:14
setTimeout (assíncrono)
hiwire_call_bound @ pyodide.asm.js:14
$func380 @ pyodide.asm.wasm:0xef536
$func3167 @ pyodide.asm.wasm:0x201f1b
$_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x1ff173
$_PyEval_Vector @ pyodide.asm.wasm:0x1f98b5
$_PyFunction_Vectorcall @ pyodide.asm.wasm:0x135329
$func1080 @ pyodide.asm.wasm:0x136c6e
$PyVectorcall_Call @ pyodide.asm.wasm:0x135186
$_PyObject_Call @ pyodide.asm.wasm:0x135243
$PyObject_Call @ pyodide.asm.wasm:0x1352e6
$_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x1fff83
$_PyEval_Vector @ pyodide.asm.wasm:0x1f98b5
$_PyFunction_Vectorcall @ pyodide.asm.wasm:0x135329
$func1080 @ pyodide.asm.wasm:0x136c6e
$func3167 @ pyodide.asm.wasm:0x201f1b
$_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x1ffa4e
$_PyEval_Vector @ pyodide.asm.wasm:0x1f98b5
$_PyFunction_Vectorcall @ pyodide.asm.wasm:0x135329
$_PyObject_FastCallDictTstate @ pyodide.asm.wasm:0x134d4d
$_PyObject_Call_Prepend @ pyodide.asm.wasm:0x13552f
$func2435 @ pyodide.asm.wasm:0x1932a4
$func2336 @ pyodide.asm.wasm:0x18ad4c
method_call_trampoline @ pyodide.asm.js:14
$_PyObject_MakeTpCall @ pyodide.asm.wasm:0x134c2c
$func3167 @ pyodide.asm.wasm:0x201efe
$_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x1ffa4e
$_PyEval_Vector @ pyodide.asm.wasm:0x1f98b5
$_PyFunction_Vectorcall @ pyodide.asm.wasm:0x135329
$func3167 @ pyodide.asm.wasm:0x201f1b
$_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x1ff9ff
$_PyEval_Vector @ pyodide.asm.wasm:0x1f98b5
$_PyFunction_Vectorcall @ pyodide.asm.wasm:0x135329
$func3167 @ pyodide.asm.wasm:0x201f1b
$_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x1ffa4e
$_PyEval_Vector @ pyodide.asm.wasm:0x1f98b5
$_PyFunction_Vectorcall @ pyodide.asm.wasm:0x135329
$func3167 @ pyodide.asm.wasm:0x201f1b
$_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x1ff9d9
$_PyEval_Vector @ pyodide.asm.wasm:0x1f98b5
$_PyFunction_Vectorcall @ pyodide.asm.wasm:0x135329
$_pyproxy_apply @ pyodide.asm.wasm:0xf16d8
Module.callPyObjectKwargs @ pyproxy.gen.ts:360
Module.callPyObject @ pyproxy.gen.ts:384
apply @ pyproxy.gen.ts:1145
apply @ pyproxy.gen.ts:1022
loadPackage @ interpreter.ts:28
loadEnv @ pyenv.ts:42
initialize @ pyconfig.ts:70
await in initialize (assíncrono)
(anônimo) @ pyconfig.ts:133
load (assíncrono)
loadRuntimes @ pyconfig.ts:132
connectedCallback @ pyconfig.ts:116
(anônimo) @ main.ts:27
(anônimo) @ main.ts:35
Mostrar mais 130 frames
pyodide.asm.js:14 Uncaught (in promise) PythonError: Traceback (most recent call last):
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 234, in __step
    result = coro.throw(exc)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 183, in install
    transaction = await self.gather_requirements(requirements, ctx, keep_going)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 173, in gather_requirements
    await gather(*requirement_promises)
  File "/lib/python3.10/asyncio/futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "/lib/python3.10/asyncio/tasks.py", line 304, in __wakeup
    future.result()
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 234, in __step
    result = coro.throw(exc)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 280, in add_requirement
    metadata = await _get_pypi_json(req.name)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 86, in _get_pypi_json
    return json.loads(await fetch_string(url))
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 58, in fetch_string
    return await (await pyfetch(url, **kwargs)).string()
  File "/lib/python3.10/site-packages/pyodide/http.py", line 231, in pyfetch
    url, await _jsfetch(url, to_js(kwargs, dict_converter=Object.fromEntries))
  File "/lib/python3.10/asyncio/futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "/lib/python3.10/asyncio/tasks.py", line 304, in __wakeup
    future.result()
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
JsException: TypeError: Failed to fetch

    at new_error (pyodide.asm.js:14:238191)
    at pyodide.asm.wasm:0xedbcb
    at pyodide.asm.wasm:0xf1a0e
    at method_call_trampoline (pyodide.asm.js:14:238105)
    at pyodide.asm.wasm:0x134c2c
    at pyodide.asm.wasm:0x217a84
    at pyodide.asm.wasm:0x174a14
    at pyodide.asm.wasm:0x135149
    at pyodide.asm.wasm:0x135243
    at pyodide.asm.wasm:0x1352e6
    at pyodide.asm.wasm:0x1fff83
    at pyodide.asm.wasm:0x1f98b5
    at pyodide.asm.wasm:0x135329
    at pyodide.asm.wasm:0x201f1b
    at pyodide.asm.wasm:0x1ff9ff
    at pyodide.asm.wasm:0x1f98b5
    at pyodide.asm.wasm:0x135329
    at pyodide.asm.wasm:0xf16d8
    at Module.callPyObjectKwargs (pyproxy.gen.ts:360:23)
    at Module.callPyObject (pyproxy.gen.ts:384:17)
    at wrapper (pyodide.asm.js:14:205222)
```

**Comment by tedpatrick** [comment]
The `sqlite3` module is part of the python standard library and is bundled within the piodide release. It does not need to be loaded via `<py-env>` or `<py-config>` to be imported and used within your app.

example:
```html
<html>
<head>
    <link rel="stylesheet" href="https://pyscript.net/unstable/pyscript.css" />
    <script defer src="https://pyscript.net/unstable/pyscript.js"></script>
</head>
<body>
    <py-script>
import sqlite3
print( sqlite3.version )
    </py-script>
</body>
</html>
```
