### ISSUE TITLE
ConsoleMessageCollection doesn't collect all console messages

### ISSUE THREAD

**Issue by marimeireles** [pyscript/pyscript#795]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

We have a helper object to collect console messages: 

https://github.com/pyscript/pyscript/blob/b674515d06a936008a13b74d4d8f74e0327eed3c/pyscriptjs/tests/integration/support.py#L274-L339

I can't figure out why but this class doesn't collect all messages. Here's an example:

I'm trying to throw an error while using the REPL and catch the console output. Here's the code that I'm using to achieve that:

```
    def test_repl_error_ouput_console(self):
        self.pyscript_run(
            """
            <py-repl id="my-repl" auto-generate="true"> </py-repl>
            """
        )
        self.page.locator("py-repl").type("this is an error")
        self.page.locator("button").click()
        console_text = self.console.all.lines
        for t in console_text:
             print('🔥', t)
        print('☀️')
        self.page.on("console", lambda msg: print('🌸', msg.text))
        print('☀️')
```

This will produce the following output:

```
🔥 [pyscript/main] checking for py-confing
🔥 [py-config] config set: {autoclose_loader: true, runtimes: Array(1)}
🔥 [py-config] Initializing runtimes
🔥 [pyscript/pyodide] Runtime config: {name: pyodide-default, lang: python, src: https://cdn.jsdelivr.net/pyodide/v0.21.2/full/pyodide.js}
🔥 [pyscript/main] add py-loader
🔥 [py-loader] Loading runtime...
🔥 [pyscript/pyodide] Loading pyodide
🔥 Python initialization complete
🔥 [pyscript/pyodide] pyodide.loadPackage: micropip
🔥 [pyscript/pyodide] Loading micropip, pyparsing, packaging, distutils
🔥 [pyscript/pyodide] Loaded micropip, pyparsing, packaging, distutils
🔥 [pyscript/pyodide] importing pyscript.py
🔥 [pyscript/pyodide] pyodide loaded and initialized
🔥 [py-loader] Runtime created...
🔥 [py-loader] Initializing components...
🔥 [py-script] py-mount: found 0 elements
🔥 [py-loader] Initializing scripts...
🔥 [py-loader] Running post initializers...
🔥 [py-repl] element my-repl successfully connected
🔥 [py-loader] Closing
🔥 [py-script] Initializing py-* event handlers...
🔥 [pyscript/runtime] PyScript page fully initialized
☀️
☀️
PASSED[  3.06 console.error  ] [pyscript/base] PythonError: Traceback (most recent call last):
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 232, in __step
    result = coro.send(None)
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 506, in eval_code_async
    await CodeRunner(
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 241, in __init__
    self.ast = next(self._gen)
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 142, in _parse_and_compile_gen
    mod = compile(source, filename, mode, flags | ast.PyCF_ONLY_AST)
  File "<exec>", line 1
    this is an error
               ^^^^^
SyntaxError: invalid syntax

🌸 [pyscript/base] PythonError: Traceback (most recent call last):
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 232, in __step
    result = coro.send(None)
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 506, in eval_code_async
    await CodeRunner(
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 241, in __init__
    self.ast = next(self._gen)
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 142, in _parse_and_compile_gen
    mod = compile(source, filename, mode, flags | ast.PyCF_ONLY_AST)
  File "<exec>", line 1
    this is an error
               ^^^^^
SyntaxError: invalid syntax
```

As you can see the last console.error is not being caught by the `ConsoleMessageCollection` class... I wonder if it's some async method behind it because it's not printed sequentially (in between the sun emojis)... 
Should we just add this method? `page.on("console",  ...)` into our object and try to incorporate this there?
Or any idea on what's happening here? @antocuni

**Comment by marimeireles** [comment]
Thanks for the review.
I'll check this later this week. :)

**Comment by antocuni** [comment]
@marimeireles PR #874 should fix it
