### ISSUE TITLE
Unable to set different runtime if direct downloading it

### ISSUE THREAD

**Issue by FabioRosado** [pyscript/pyscript#969]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

I'm writing a tutorial for setting a different runtime and thought about simply doing:

```html
    <py-config>
      [[runtimes]]
      src = "https://github.com/pyodide/pyodide/releases/download/0.20.0/pyodide-build-0.20.0.tar.bz2"
      name = "pyodide"
      lang = "python"
    </py-config>
    <py-script>
      import pyodide
      print(pyodide.__version__)
    </py-script>
```

But this doesn't work because we can't unzip the file and use it, this is probably obvious although I kind of wish it would just work.

### What browsers are you seeing the problem on? (if applicable)

Chrome

### Console info

```shell
[pyscript/main] searching for <py-config>
logger.ts:39 [py-config] loading <py-config> content
logger.ts:39 [pyscript/main] config loaded:
{
  "type": "app",
  "schema_version": 1,
  "runtimes": [
    {
      "src": "https://github.com/pyodide/pyodide/releases/download/0.20.0/pyodide-build-0.20.0.tar.bz2",
      "name": "pyodide",
      "lan": "en"
    }
  ],
  "packages": [],
  "fetch": [],
  "plugins": [],
  "pyscript": {
    "version": "2022.11.1.dev",
    "time": "2022-11-21T21:08:27.739Z"
  }
}
logger.ts:39 [py-splashscreen] add py-splashscreen
logger.ts:39 [py-terminal] No <py-terminal> found, adding one
logger.ts:39 [pyscript/main] Initializing runtime
logger.ts:39 [pyscript/pyodide] Runtime config: {name: 'pyodide', lang: 'python', src: 'https://github.com/pyodide/pyodide/releases/download/0.20.0/pyodide-build-0.20.0.tar.bz2'}lang: "python"name: "pyodide"src: "https://github.com/pyodide/pyodide/releases/download/0.20.0/pyodide-build-0.20.0.tar.bz2"[[Prototype]]: Object
logger.ts:39 [pyscript/main] Downloading pyodide...
pyodide-build-0.20.0.tar.bz2:1 Uncaught SyntaxError: Invalid or unexpected token (at pyodide-build-0.20.0.tar.bz2:1:13)
logger.ts:39 [pyscript/main] Python startup...
logger.ts:39 [pyscript/pyodide] Loading pyodide
pyodide.ts:36 Uncaught (in promise) ReferenceError: loadPyodide is not defined
    at PyodideRuntime.loadInterpreter (pyodide.ts:36:28)
    at PyScriptApp.afterRuntimeLoad (main.ts:141:23)
    at HTMLScriptElement.<anonymous> (main.ts:127:18)
```

### Additional Context

Mind you that this is mostly me not understanding fully how our `py-config` works yet 😄

**Comment by WebReflection** [comment]
the `runtimes` things never worked as expected and it's non-existent in current PyScript so I *think* this can be closed.

**Comment by WebReflection** [comment]
P.S. we have `interpreter` field now and it's global per main scope or worker env.
